import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {ConfigSchema} from '../packages/core/config.js';
import {ShotSchema,type Shot} from '../packages/core/schemas.js';
import {ActorDefinitionSchema} from '../packages/actors/schemas.js';
import {actorProfile} from '../packages/actors/model.js';
import {buildRig} from '../packages/host/rig.js';
import {rigMetrics} from '../packages/animation/rig.js';
import {PerformancePlanSchema,ANIMATION_VERSION,type PerformancePlan} from '../packages/animation/schemas.js';
import {samplePerformance,compilePerformance,validatePerformance} from '../packages/animation/compiler.js';
import {performanceScene} from '../packages/animation/scene.js';
import {DIRECTION_VERSION} from '../packages/director/schemas.js';
import {stageModels} from '../packages/director/models.js';
import {modelExitParts,validatePropBindings,PROP_BINDING_VERSION} from '../packages/director/props.js';
import {validateCinematicShot} from '../packages/director/index.js';
import {renderCinematic} from '../library/shots/cinematic.js';
import {secureSceneFiles,validateSceneScript} from '../packages/scenes/security.js';
import {cinematicActionGroups} from '../packages/director/actions.js';
const silence={method:'segment-draft' as const,windowMs:20,intervals:[]};
const config=ConfigSchema.parse({presentation:{mode:'story-cinematic',character_mode:'actors'},rendering:{final:{width:1280,height:720,fps:30}}});
const ref={kind:'narration' as const,segmentId:'cue',quote:'A researcher separates a cold condenser. Steam travels to the condenser.'};
function retain(name:string,data:unknown){const root=process.env.ACTING_RUNTIME_EVIDENCE;if(root)writeFileSync(path.join(root,name+'.json'),JSON.stringify(data,null,2));}
function actor(kind:'stick-man'|'mini-robot'){return ActorDefinitionSchema.parse({id:'researcher',name:'Researcher',role:'illustrates separation',identity:'illustrative',kind,sourceRefs:[ref],appearance:{outline:'#17363F',shell:'#F7E4BD',screen:'#203742',accent:'#ECFFFF',badge:'#DAB26B',headScale:1,bodyScale:1,strokeWidth:6},costume:[]});}
function plain(kind:'stick-man'|'mini-robot') {const profile=actorProfile(actor(kind));const plan=PerformancePlanSchema.parse({version:22,compilerVersion:ANIMATION_VERSION,id:'transport-audit',leadCharacterId:profile.id,profileHash:profile.profileHash,kind,durationMs:6000,fps:30,stage:{width:1280,height:720,groundY:550},root:{x:640,y:550},scale:1,facing:'front',walks:[],gestures:[],expressions:[],gazes:[],props:[]});return {profile,plan};}
const nums=(value:string)=>{const found=value.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi);assert.ok(found,`missing transform ${value}`);return found.map(Number);};
const xy=(value:string)=>{const n=nums(value);return {x:n[0]!,y:n[1]!};};
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
function gsap(js:string,id:string){
  assert.deepEqual(validateSceneScript(js,id),[],'untrusted scene code must never execute');const targets=new Map<string,Record<string,unknown>>();
  const canonical=(selector:string)=>selector.replace(/#object-\d+ (\.focus-\d+)$/,'$1'); const document={createElement:()=>({style:{}}),documentElement:{},querySelectorAll:(selector:string)=>{selector=canonical(selector);let target=targets.get(selector);if(!target){const attr:Record<string,string>={};target={x:0,y:0,opacity:1,rotation:0,scaleY:1,getAttribute:(key:string)=>attr[key]??'',setAttribute:(key:string,value:string)=>{attr[key]=String(value);}};targets.set(selector,target);}return [target];}};
  const context=vm.createContext({window:{document},document,console,setTimeout:()=>0,clearTimeout:()=>{},Date});vm.runInContext(readFileSync(createRequire(import.meta.url).resolve('gsap/dist/gsap.js'),'utf8'),context);vm.runInContext(`var gsap=window.gsap;${js};gsap.ticker.sleep();`,context);
  const timeline=context.window.__timelines[id] as {seek:(t:number,suppress:boolean)=>unknown};return {seek:(ms:number)=>timeline.seek(ms/1000,true),attr:(selector:string)=>{const t=targets.get(canonical(`[data-composition-id="${id}"] ${selector}`));assert.ok(t,`missing target ${selector}`);return (t.getAttribute as (key:string)=>string)('transform');},value:(selector:string,key:string)=>targets.get(canonical(`[data-composition-id="${id}"] ${selector}`))?.[key]};
}
// Fresh current public-schema fixture: per-hand reachable world layout, not retagged artist output.
function transport(kind:'stick-man'|'mini-robot',hand:'left'|'right'){
  const {profile,plan}=plain(kind),m=rigMetrics(profile),sign=hand==='left'?-1:1;plan.root.x=hand==='left'?720:470;plan.facing=hand;
  const grip={x:plan.root.x+sign*(m.shoulderOffset+45),y:550+m.shoulderY+20},offset={x:-1280*.07*.35,y:0},center={x:grip.x-offset.x,y:grip.y},destination={x:center.x+sign*100,y:center.y};
  plan.walks=[{startMs:900,endMs:3000,fromX:plan.root.x,toX:plan.root.x+sign*100}];plan.props=[{id:'condenser-prop',origin:center,destination,gripOffset:offset}];plan.gestures=[{id:'carry-condenser',propId:'condenser-prop',hand,action:'carry',startMs:0,endMs:4000,contactMs:600,releaseMs:3700,target:grip,destination:{x:destination.x+offset.x,y:destination.y},carryOffset:{x:sign*55,y:-25}}];
  const shot=ShotSchema.parse({id:plan.id,startMs:1000,endMs:7000,beatIds:['beat'],sceneType:'character-scene',subject:'Sourced separation illustration',characters:[profile.id],visualDescription:'Researcher lifts, carries and releases the illustrative cold condenser.',camera:{shotSize:'wide',movement:'locked',angle:'eye-level'},recipeId:'host-mechanism-explainer',renderer:'hyperframes',narrationSegmentIds:['cue'],sourceRefs:[ref],host:{id:profile.id,profileVersion:1,rigHash:buildRig(profile).rigHash,presence:'beside-model',actions:[{type:'operate-model',hand,startMs:1000,endMs:5000,contactMs:1600,narrationAnchor:'cue',target:{modelId:'audit-model',partId:'condenser',anchor:'handle'}}]},visualization:{type:'mechanism',modelId:'audit-model',provenance:'visualization',fidelity:'conceptual',parts:[{id:'steam',label:'Steam',kind:'flow',x:(hand==='left'?950:210)/1280,y:(center.y-20)/720,width:.08,height:.04,sourceRefs:[ref]},{id:'condenser',label:'cold condenser',kind:'condenser',x:center.x/1280,y:center.y/720,width:.07,height:.12,sourceRefs:[ref],states:[{value:'cold',sourceRefs:[ref]}]}],relations:[{from:'steam',to:'condenser',kind:'transfer',sourceRefs:[ref]}],events:[{type:'state',targetId:'condenser',state:'cold',startMs:1000,endMs:7000,motion:'none',contactRequired:false,narrationAnchor:'cue',sourceRefs:[ref]},{type:'highlight',targetId:'condenser',contactPartId:'condenser',startMs:1601,endMs:5000,motion:'none',contactRequired:true,narrationAnchor:'cue',sourceRefs:[ref]},{type:'flow',targetId:'steam',relationTo:'condenser',startMs:3300,endMs:4600,motion:'translate',contactRequired:false,narrationAnchor:'cue',sourceRefs:[ref]}]}});
  shot.cinematic={version:22,producer:DIRECTION_VERSION,shotId:shot.id,leadCharacterId:profile.id,motivation:'Illustrative separation supported by the narration.',attentionPartId:'condenser',sourceRefs:[ref],setting:'workshop',provenance:'illustration',models:stageModels(shot),propBindings:[{propId:'condenser-prop',partId:'condenser',role:'illustrative-model',sourceRefs:[ref]}],actorScene:{primary:actor(kind),speakingSegmentIds:[],continuity:'cut',supporting:[]},artDirection:{origin:'authored',brief:'Current-source audit composition with physical supports and reachable per-hand transport; no historical reenactment claim.',useEnvironment:false,palette:{background:'#17363F',surface:'#F7E4BD',ink:'#17363F',accent:'#DAB26B'},showHeading:false,layers:[],models:[{partId:'condenser',sourceRefs:[ref],svg:'<rect x="-40" y="-35" width="80" height="70" fill="#BBDDED"/>',labelMode:'renderer',controlMode:'none'}]},continuity:{entry:plan.root,exit:{x:plan.walks[0]!.toX,y:550},facing:hand,carriedProps:[],models:[]},camera:{framing:'wide',movement:'locked',focus:'ensemble',anchor:{x:640,y:330},startScale:1,endScale:1,designIntent:'Keep the whole transport, both fixed supports and labels inside the action viewport.'},performance:plan};
  const declared=shot.visualization!.parts.find(p=>p.id==='condenser')!;plan.props[0]!.origin={x:declared.x*plan.stage.width,y:declared.y*plan.stage.height}; shot.cinematic.continuity.models=modelExitParts(shot).map(p=>({partId:p.id,x:p.x,y:p.y,width:p.width,height:p.height}));return {shot,profile,rig:buildRig(profile),plan};
}
function bones(transforms:Record<string,string>,m:ReturnType<typeof rigMetrics>,scale:number,tolerance:number){for(const side of ['left','right'])for(const [a,b,length] of [[`arm-${side}-upper`,`arm-${side}-lower`,m.upperArm],[`arm-${side}-lower`,`hand-${side}`,m.lowerArm],[`leg-${side}-upper`,`leg-${side}-lower`,m.upperLeg],[`leg-${side}-lower`,`foot-${side}`,m.lowerLeg]] as const){const n=nums(transforms[a]!),r=n[2]!*Math.PI/180;const end={x:n[0]!-Math.sin(r)*length*n[3]!,y:n[1]!+Math.cos(r)*length*n[3]!};assert.ok(dist(end,xy(transforms[b]!))<tolerance,`${a} joint disconnect`);assert.ok(Math.abs(dist(xy(transforms[a]!),xy(transforms[b]!))-length*scale)<tolerance,`${a} length changed`);}}
for(const kind of ['stick-man','mini-robot'] as const){
  for(const pose of ['crouch','lean'] as const)test(`${kind}: held ${pose} returns to stand before walking, with planted feet/bones and GSAP random seeks`,()=>{
    const {profile,plan}=plain(kind);plan.postures=[{startMs:100,endMs:600,pose,intensity:.65},{startMs:1600,endMs:2100,pose:'stand'}];plan.walks=[{startMs:2200,endMs:4000,fromX:640,toX:710}];const compiled=compilePerformance(plan,profile,silence),m=rigMetrics(profile),scene=secureSceneFiles(performanceScene(plan,profile,silence).files),probe=gsap(scene.files.find(f=>f.path==='scene.js')!.content,plan.id);const frames=[0,400,600,950,1400,1600,1900,2100,2300,3000,4100].map(ms=>samplePerformance(plan,profile,ms,silence));
    retain(kind+'-'+pose,{plan,frames,report:compiled.report});assert.deepEqual(frames[3]!.bodyPosture,frames[4]!.bodyPosture);assert.ok(frames[3]!.bodyPosture.leanDeg!==0);for(const f of frames){bones(f.transforms,m,1,.003);if(f.timeMs<=2100)assert.deepEqual(f.feet,frames[0]!.feet);}
    for(const ms of [4100,950,3000,600,0,1400,2100]){probe.seek(ms);const f=samplePerformance(plan,profile,ms,silence);for(const id of ['pelvis','foot-left','foot-right','arm-left-lower','arm-right-lower'])assert.ok(dist(xy(probe.attr('#'+id)),xy(f.transforms[id]!))<.21);}
    for(const mutate of [(p:PerformancePlan)=>{p.postures![0]!.endMs=300;},(p:PerformancePlan)=>{p.postures![1]!.startMs=400;},(p:PerformancePlan)=>{p.walks[0]!.startMs=1900;},(p:PerformancePlan)=>{p.postures![0]!.intensity=1.1;},(p:PerformancePlan)=>{p.postures![0]!.leanDeg=26;},(p:PerformancePlan)=>{p.postures![0]!.leanDeg=NaN;}]){const bad=structuredClone(plan);mutate(bad);assert.throws(()=>compilePerformance(bad,profile,silence));}
  });
  test(`${kind}: concurrent hand contacts and an opposite-arm interlude preserve a held point`,()=>{
    const {profile,plan}=plain(kind),idle=samplePerformance(plan,profile,0,silence);plan.gestures=(['left','right'] as const).map(hand=>({id:'hold-'+hand,hand,action:'operate' as const,startMs:200,endMs:3000,contactMs:600,target:{x:idle.hands[hand].x,y:idle.hands[hand].y-25}}));const compiled=compilePerformance(plan,profile,silence),probe=gsap(secureSceneFiles(performanceScene(plan,profile,silence).files).files.find(f=>f.path==='scene.js')!.content,plan.id);
    retain(kind+'-bilateral',{plan,report:compiled.report});for(const ms of [600,1800,2600,900,2000]){probe.seek(ms);const f=samplePerformance(plan,profile,ms,silence);for(const hand of ['left','right'] as const){assert.ok(dist(f.hands[hand],plan.gestures.find(g=>g.hand===hand)!.target!)<.001);assert.ok(dist(xy(probe.attr('#hand-'+hand)),f.hands[hand])<.21);}}
    for(const issue of ['same-hand','duplicate','old-hand'] as const){const bad=structuredClone(plan);if(issue==='same-hand')bad.gestures[1]!.hand='left';if(issue==='duplicate')bad.gestures[1]!.id=bad.gestures[0]!.id;if(issue==='old-hand')bad.compilerVersion='performance-2.2.8';assert.throws(()=>validatePerformance(bad,profile));}
    const held=plain(kind).plan;held.gestures=[{id:'long-point',hand:'left',action:'point',startMs:300,endMs:4000,target:{x:480,y:380}},{id:'interlude',hand:'right',action:'think',startMs:1300,endMs:2400}];const c=compilePerformance(held,profile,silence);const runtime=gsap(secureSceneFiles(performanceScene(held,profile,silence).files).files.find(f=>f.path==='scene.js')!.content,held.id);const target=samplePerformance(held,profile,900,silence).hands.left;for(const ms of [900,1400,2000,2500,3400,1400]){runtime.seek(ms);assert.ok(dist(samplePerformance(held,profile,ms,silence).hands.left,target)<.001);assert.ok(dist(xy(runtime.attr('#hand-left')),target)<.21);}assert.ok(c.frames.length>1);
  });
  test(`${kind}: legacy7/8/9 omit-hand plans retain right-hand behavior; new fields reject old versions`,()=>{
    const {profile,plan}=plain(kind);plan.gestures=[{id:'old-point',action:'point',startMs:500,endMs:2500,target:{x:790,y:350}}];const expected=samplePerformance(plan,profile,1500,silence).transforms;for(const version of ['performance-2.2.7','performance-2.2.8','performance-2.2.9'] as const){const legacy={...plan,compilerVersion:version};assert.doesNotThrow(()=>validatePerformance(legacy,profile));assert.deepEqual(samplePerformance(legacy,profile,1500,silence).transforms,expected);}
    assert.throws(()=>validatePerformance({...plan,compilerVersion:'performance-2.2.7',postures:[{startMs:0,endMs:400,pose:'lean'}]},profile));for(const version of ['performance-2.2.7','performance-2.2.8'] as const)assert.throws(()=>validatePerformance({...plan,compilerVersion:version,gestures:[{...plan.gestures[0]!,hand:'left'}]},profile));
  });
  for(const hand of ['left','right'] as const)test(`${kind}/${hand}: released carry grip/center and moving label, thermal, emphasis, energy, shadow and relation survive secured real GSAP`,()=>{
    const {shot,profile,rig,plan}=transport(kind,hand),prop=plan.props[0]!,offset=prop.gripOffset!;assert.doesNotThrow(()=>validateCinematicShot(shot,profile,config));const rendered=renderCinematic(shot,profile,rig,silence,config),files=secureSceneFiles(rendered.files),js=files.files.find(f=>f.path==='scene.js')!.content,html=files.files.find(f=>f.path==='index.html')!.content;const root=process.env.ACTING_RUNTIME_EVIDENCE;if(root)for(const f of files.files)writeFileSync(path.join(root,kind+'-'+hand+'-'+f.path),f.content);const probe=gsap(js,shot.id),rows=[];assert.equal(rendered.report.boundModelMotionVersion,PROP_BINDING_VERSION);assert.match(html,/class="model-label"/);assert.match(html,/thermal-coat/);assert.ok(!html.includes('data-control="illustrative"'),'no synthetic crank for controlMode none');
    for(const ms of [600,850,2000,3000,3450,3600,3699.999,3700,4000]){probe.seek(ms);const f=samplePerformance(plan,profile,ms,silence),center=f.props[prop.id]!.point;if(ms<3700){assert.equal(f.props[prop.id]!.attached,true);assert.ok(dist({x:center.x+offset.x,y:center.y+offset.y},f.hands[hand])<.001);assert.ok(dist(center,f.hands[hand])>20);}else{assert.equal(f.props[prop.id]!.attached,false);assert.ok(dist(center,prop.destination!)<.000001);}
      assert.ok(dist(xy(probe.attr('#prop-'+prop.id)),center)<.21);const overlay=xy(probe.attr('#object-1')),shadow=xy(probe.attr('#object-1 .bound-model-shadow')),arrow=xy(probe.attr('#relation-0-arrow'));assert.ok(dist({x:overlay.x+prop.origin.x,y:overlay.y+prop.origin.y},center)<.21);assert.ok(Math.abs(overlay.y+shadow.y)<.21);assert.ok(dist(arrow,center)<100);rows.push({ms,center,overlay,shadow,arrow});}
    retain(kind+'-'+hand+'-carry',{shot,rows,report:rendered.report});assert.ok(rows[1]!.center.y<prop.origin.y-10);assert.ok(Math.abs(rows[2]!.center.x-rows[1]!.center.x)>20);assert.ok(rows[5]!.center.y>rows[4]!.center.y);probe.seek(2800);assert.ok(Number(probe.value('#relation-flow-0','opacity'))>0);assert.ok(Number(probe.value('#object-1 .focus-1','opacity'))>0);assert.ok(Math.abs(Number(probe.value('#prop-condenser-prop .thermal-cold-coat','opacity'))-.62)<.00001,'visible cold coat uses translucent .62');probe.seek(3300);assert.ok(Number(probe.value('#object-1 .energy-effect','opacity'))>0);for(const row of [...rows].reverse()){probe.seek(row.ms);assert.ok(dist(xy(probe.attr('#relation-0-arrow')),row.arrow)<.001);assert.ok(dist(xy(probe.attr('#object-1')),row.overlay)<.001);}
  });
}
for(const issue of ['center','owner-hand','owner-clock','stale-target','joint-owner','entry','unreleased','repeat','source','duplicate-binding'] as const)test(`bound model rejects ${issue}`,()=>{
  const {shot}=transport('mini-robot','right');assert.doesNotThrow(()=>validatePropBindings(shot));const c=shot.cinematic!,g=c.performance.gestures[0]!,p=c.performance.props[0]!;
  if(issue==='center')p.destination=g.destination;if(issue==='owner-hand')shot.host!.actions[0]!.hand='left';if(issue==='owner-clock')shot.host!.actions[0]!.endMs--;if(issue==='stale-target')shot.host!.actions.push({...shot.host!.actions[0]!,type:'point',contactMs:undefined,startMs:2000,endMs:3000});if(issue==='joint-owner')shot.host!.actions.push({...shot.host!.actions[0]!,hand:'left'});if(issue==='entry')p.attachedTo='right-hand';if(issue==='unreleased')g.releaseMs=undefined;if(issue==='repeat')c.performance.gestures.push({...g,id:'repeat'});if(issue==='source')c.propBindings[0]!.sourceRefs=[{...ref,quote:'invented'}];if(issue==='duplicate-binding'){c.propBindings.push({...c.propBindings[0]!,propId:'other'});c.performance.props.push({...p,id:'other'});}
  assert.throws(()=>validatePropBindings(shot));retain('reject-'+issue,shot);
});
test('cue grouping is per hand: an intervening opposite-arm cue does not restart a held point',()=>{const {plan}=plain('stick-man');plan.gestures=[{id:'held',hand:'left',action:'point',startMs:0,endMs:3000,target:{x:500,y:380}},{id:'other',hand:'right',action:'think',startMs:700,endMs:1600}];const actions=[{type:'point' as const,hand:'left' as const,startMs:0,endMs:1000,target:{modelId:'m',partId:'p',anchor:'center' as const}},{type:'think' as const,hand:'right' as const,startMs:700,endMs:1600},{type:'point' as const,hand:'left' as const,startMs:1000,endMs:3000,target:{modelId:'m',partId:'p',anchor:'center' as const}}];const groups=cinematicActionGroups(actions,plan,0);assert.equal(groups.filter(g=>g.action.hand==='left').length,1);assert.equal(groups.find(g=>g.action.hand==='left')!.gestures[0]!.id,'held');});
test('Scene JS rejects matrices, arbitrary attributes, path mutation, callbacks and external code',()=>{for(const field of ['transform:"matrix(1 0 0 1 0 0)"','d:"M0 0L10 10"','href:"https://invalid.test"']){const js=`const tl=gsap.timeline({paused:true});window.__timelines=window.__timelines||{};window.__timelines["x"]=tl;tl.set('[data-composition-id="x"] #p',{attr:{${field}}},0);`;assert.ok(validateSceneScript(js,'x').length);}assert.ok(validateSceneScript('fetch("https://invalid.test")','x').length);});