import assert from 'node:assert/strict';
import test from 'node:test';
import { temporary } from './support.js';
import { ConfigSchema } from '../packages/core/config.js';
import { BeatSchema, StorySchema, type Narration } from '../packages/core/schemas.js';
import { compileHost } from '../packages/host/index.js';
import { ModelRouter } from '../packages/models/registry.js';
import { groundedExplanation } from '../packages/explainer/plan.js';
import { explainerShot, validateExplainerStoryboard } from '../packages/explainer/storyboard.js';
import { directCinematicShot, validateModelContinuity } from '../packages/director/index.js';
import { modelExitParts } from '../packages/director/props.js';
import { samplePerformance } from '../packages/animation/compiler.js';
import { renderCinematic } from '../library/shots/cinematic.js';
import { secureSceneFiles } from '../packages/scenes/security.js';
import { validateCinematicEdit } from '../apps/server/cinematic.js';

const activity={method:'audio-rms' as const,windowMs:20,intervals:[{startMs:0,endMs:8000,level:.5}]};
for(const kind of ['stick-man','mini-robot'] as const)test(`${kind}: a narrated model pickup uses the actual sourced battery through production and API`,async t=>{
  const root=await temporary(t),config=ConfigSchema.parse({presentation:{mode:'story-cinematic'},host:{profile:`library/characters/${kind==='stick-man'?'STICK-MAN':'MINI-ROBOT'}.md`},rendering:{final:{width:1280,height:720,fps:30}}});
  const {profile,rig}=await compileHost(root,config,new ModelRouter(config,root));
  const text='Ta nhấc pin lên rồi đặt pin sang bên phải.',narration:Narration={mode:'srt',durationMs:8000,segments:[{id:'cue',startMs:0,endMs:8000,text}],words:[]};
  const story=StorySchema.parse({title:'Thao tác mô hình',story:text,style:{visual:'vector'}}),base=BeatSchema.parse({id:'b1',chapterId:'ch1',startMs:0,endMs:8000,segmentIds:['cue'],narrationText:text,meaning:'process',visualGoal:'show narrated pickup',importance:1});
  const beat={...base,...groundedExplanation(story,narration,[base],profile).beats[0]!},shot=directCinematicShot(explainerShot('s1',0,8000,beat,narration,profile,rig),beat,profile,config);
  const p=shot.cinematic!.performance,g=p.gestures.find(g=>g.action==='pick-place');assert.ok(g,'production needs a real pickup, not a pointing substitute');
  assert.equal(p.props.length,1);assert.ok(g.propId&&g.releaseMs);
  const contact=samplePerformance(p,profile,g.contactMs!,activity),hold=samplePerformance(p,profile,(g.contactMs!+g.releaseMs!)/2,activity),release=samplePerformance(p,profile,g.releaseMs!,activity);
  assert.equal(contact.props[g.propId!]!.attached,true);assert.equal(hold.props[g.propId!]!.attached,true);assert.equal(release.props[g.propId!]!.attached,false);
  assert.ok(Math.hypot(hold.hands.right.x-hold.props[g.propId!]!.point.x,hold.hands.right.y-hold.props[g.propId!]!.point.y)<.01);
  assert.deepEqual(release.props[g.propId!]!.point,g.destination);
  validateExplainerStoryboard({shots:[shot]},narration,[beat],profile,rig,config);
  assert.doesNotThrow(()=>validateCinematicEdit({shots:[shot]},config));
  const qualified=structuredClone(shot);qualified.cinematic!.propBindings[0]!.ownerId=qualified.cinematic!.leadCharacterId;
  validateExplainerStoryboard({shots:[qualified]},narration,[beat],profile,rig,config);
  assert.doesNotThrow(()=>validateCinematicEdit({shots:[qualified]},config));
  const qualifiedRender=renderCinematic(qualified,profile,rig,activity,config);
  assert.equal(qualifiedRender.report.boundModels?.[0]?.actorId,qualified.cinematic!.leadCharacterId);
  qualified.cinematic!.propBindings[0]!.ownerId='invented-person';
  assert.throws(()=>validateCinematicEdit({shots:[qualified]},config),/not one visible/);
  const rendered=renderCinematic(shot,profile,rig,activity,config),files=secureSceneFiles(rendered.files),html=files.files.find(f=>f.path==='index.html')!.content;
  assert.match(html,/data-prop-entity="b1.battery"/);assert.equal((html.match(/data-prop-entity="b1.battery"/g)??[]).length,1);
  assert.ok(rendered.geometry.interactions.some(a=>a.type==='operate-model'&&a.contactMs===a.reachMs&&a.errorPx<.01));
  const forged=structuredClone(shot);forged.cinematic!.performance.gestures[0]!.target!.x+=80;
  assert.throws(()=>validateExplainerStoryboard({shots:[forged]},narration,[beat],profile,rig,config),/anchor|target|prop/i);
  const after=structuredClone(shot);after.id='s2';after.startMs=8000;after.endMs=12000;after.cinematic=undefined;
  after.host!.actions=[{type:'point',startMs:8000,endMs:12000,narrationAnchor:'next',target:{modelId:after.visualization!.modelId,partId:after.visualization!.parts[0]!.id,anchor:'center'}}];
  after.visualization!.parts[0]!.sourceRefs=[{kind:'narration',segmentId:'next',quote:'Pin là một nguồn năng lượng.'}];
  after.visualization!.events=[{type:'highlight',targetId:after.visualization!.parts[0]!.id,startMs:8000,endMs:12000,narrationAnchor:'next',contactRequired:false,motion:'none',sourceRefs:after.visualization!.parts[0]!.sourceRefs}];
  after.sourceRefs=after.visualization!.parts[0]!.sourceRefs;
  const continued=directCinematicShot(after,{...beat,narrationText:'Pin là một nguồn năng lượng.'},profile,config,shot.cinematic!.continuity.exit,{parts:modelExitParts(shot),facing:shot.cinematic!.continuity.facing});
  validateModelContinuity(shot,continued);
  assert.equal(continued.visualization!.parts[0]!.x*p.stage.width,g.destination!.x);
  const teleport=structuredClone(continued);teleport.visualization!.parts[0]!.x-=.08;
  assert.throws(()=>validateModelContinuity(shot,teleport),/teleports/,'a placed prop cannot jump back to its pickup origin');
});
