import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {ActorDefinitionSchema} from '../packages/actors/schemas.js';
import {actorProfile,validateActorCast,bindActorShot} from '../packages/actors/model.js';
import {ShotSchema,type Shot,type Narration} from '../packages/core/schemas.js';
import {ConfigSchema} from '../packages/core/config.js';
import {buildRig} from '../packages/host/rig.js';
import {rigMetrics} from '../packages/animation/rig.js';
import {ANIMATION_VERSION,PerformancePlanSchema,type PerformancePlan,type SeatSupport} from '../packages/animation/schemas.js';
import {samplePerformance,compilePerformance,validatePerformance} from '../packages/animation/compiler.js';
import {performanceScene} from '../packages/animation/scene.js';
import {sceneSeats} from '../packages/stage/seats.js';
import {sameSeatSupport} from '../packages/animation/support.js';
import {stageModels} from '../packages/director/models.js';
import {DIRECTION_VERSION} from '../packages/director/schemas.js';
import {renderCinematic} from '../library/shots/cinematic.js';
import {validateCinematicShot} from '../packages/director/index.js';
import {secureSceneFiles,validateSceneScript} from '../packages/scenes/security.js';
const silence={method:'segment-draft' as const,windowMs:20,intervals:[]};
const config=ConfigSchema.parse({presentation:{mode:'story-cinematic',character_mode:'actors'},rendering:{final:{width:1280,height:720,fps:30}}});
const ref={kind:'narration' as const,segmentId:'cue',quote:'Researchers inspect an illustrative document.'};
const narration:Narration={mode:'srt',durationMs:12000,segments:[{id:'cue',startMs:0,endMs:12000,text:ref.quote}],words:[]};
function retain(name:string,data:unknown){if(process.env.ACTING_RUNTIME_EVIDENCE)writeFileSync(path.join(process.env.ACTING_RUNTIME_EVIDENCE,name+'.json'),JSON.stringify(data,null,2));}
function character(kind:'stick-man'|'mini-robot',id='observer'){return ActorDefinitionSchema.parse({id,name:'Researcher',role:'inspects an illustrative document',kind,identity:'illustrative',sourceRefs:[ref],appearance:{outline:'#17363F',shell:'#F7E4BD',screen:'#203742',accent:'#ECFFFF',badge:'#DAB26B',headScale:1,bodyScale:1,strokeWidth:6},costume:[]});}
function fixture(kind:'stick-man'|'mini-robot',facing:'left'|'right'){
  const actor=character(kind),profile=actorProfile(actor),m=rigMetrics(profile),sign=facing==='right'?1:-1;
  const plan=PerformancePlanSchema.parse({version:22,compilerVersion:ANIMATION_VERSION,id:'seated-audit',leadCharacterId:profile.id,profileHash:profile.profileHash,kind,durationMs:6000,fps:30,stage:{width:1280,height:720,groundY:550},root:{x:640,y:550},scale:1,facing,supports:[{id:'inspection-seat',kind:'seat',center:{x:640-sign*m.upperLeg,y:550-m.lowerLeg},width:96,facing,backHeight:65}],postures:[{startMs:100,endMs:900,pose:'seated',supportId:'inspection-seat'},{startMs:1800,endMs:2080,pose:'seated',supportId:'inspection-seat',leanDeg:10},{startMs:2800,endMs:3600,pose:'stand'}],walks:[{startMs:3800,endMs:5300,fromX:640,toX:640+sign*60}],gestures:[],expressions:[],gazes:[],props:[]});
  return {actor,profile,plan,m};
}
const numbers=(v:string)=>{const ns=v.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi);assert.ok(ns,v);return ns.map(Number);};
const xy=(v:string)=>{const n=numbers(v);return {x:n[0]!,y:n[1]!};};
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
function bones(t:Record<string,string>,m:ReturnType<typeof rigMetrics>,tolerance:number){for(const side of ['left','right'])for(const [a,b,length] of [[`leg-${side}-upper`,`leg-${side}-lower`,m.upperLeg],[`leg-${side}-lower`,`foot-${side}`,m.lowerLeg],[`arm-${side}-upper`,`arm-${side}-lower`,m.upperArm],[`arm-${side}-lower`,`hand-${side}`,m.lowerArm]] as const){const n=numbers(t[a]!),r=n[2]!*Math.PI/180;assert.ok(dist({x:n[0]!-Math.sin(r)*length*n[3]!,y:n[1]!+Math.cos(r)*length*n[3]!},xy(t[b]!))<tolerance,`${a} end disconnected`);assert.ok(Math.abs(dist(xy(t[a]!),xy(t[b]!))-length)<tolerance,`${a} length changed`);}}
function probe(js:string,id:string){assert.deepEqual(validateSceneScript(js,id),[]);const targets=new Map<string,Record<string,unknown>>();const document={createElement:()=>({style:{}}),documentElement:{},querySelectorAll:(selector:string)=>{let target=targets.get(selector);if(!target){const attrs:Record<string,string>={};target={x:0,y:0,opacity:1,rotation:0,scaleY:1,getAttribute:(key:string)=>attrs[key]??'',setAttribute:(key:string,value:string)=>{attrs[key]=String(value);}};targets.set(selector,target);}return [target];}};const context=vm.createContext({window:{document},document,console,setTimeout:()=>0,clearTimeout:()=>{},Date});vm.runInContext(readFileSync(createRequire(import.meta.url).resolve('gsap/dist/gsap.js'),'utf8'),context);vm.runInContext(`var gsap=window.gsap;${js};gsap.ticker.sleep();`,context);const tl=context.window.__timelines[id] as {seek:(seconds:number,suppress:boolean)=>unknown};return {seek:(ms:number)=>tl.seek(ms/1000,true),attr:(id:string)=>{const target=targets.get(`[data-composition-id="${planId(id)}"] #${jointId(id)}`);assert.ok(target,`missing ${id}`);return (target.getAttribute as (key:string)=>string)('transform');}};function planId(_id:string){return id;}function jointId(j:string){return j;}}
function shotFor(kind:'stick-man'|'mini-robot',facing:'left'|'right'){
  const f=fixture(kind,facing),{plan,profile}=f;const shot=ShotSchema.parse({id:plan.id,startMs:0,endMs:6000,beatIds:['beat'],sceneType:'character-scene',subject:'Supported inspection',characters:[profile.id],visualDescription:'Illustrative researcher sits, inspects, stands and walks.',camera:{shotSize:'wide',movement:'locked',angle:'eye-level'},renderer:'hyperframes',recipeId:'host-mechanism-explainer',sourceRefs:[ref],narrationSegmentIds:['cue'],host:{id:profile.id,profileVersion:1,rigHash:buildRig(profile).rigHash,presence:'beside-model',actions:[{type:'idle',startMs:0,endMs:6000,narrationAnchor:'cue'}]},visualization:{type:'mechanism',modelId:'document-model',parts:[{id:'document',label:'document',kind:'object',sourceRefs:[ref],x:.25,y:.55,width:.08,height:.08}],relations:[],events:[{type:'highlight',targetId:'document',startMs:1000,endMs:2400,narrationAnchor:'cue',contactRequired:false,motion:'none',sourceRefs:[ref]}],provenance:'visualization',fidelity:'conceptual'}});
  shot.cinematic={version:22,producer:DIRECTION_VERSION,shotId:shot.id,leadCharacterId:profile.id,motivation:'Inspect a sourced illustrative document.',attentionPartId:'document',sourceRefs:[ref],setting:'workshop',provenance:'illustration',models:stageModels(shot),propBindings:[],actorScene:{primary:f.actor,speakingSegmentIds:[],continuity:'cut',supporting:[]},artDirection:{origin:'authored',brief:'A fresh current-source physical seat composition with full body, floor and support visible.',useEnvironment:false,showHeading:false,palette:{background:'#17363F',surface:'#F7E4BD',ink:'#17363F',accent:'#DAB26B'},layers:[],models:[]},continuity:{entry:plan.root,exit:{x:plan.walks[0]!.toX,y:550},facing,carriedProps:[],models:shot.visualization!.parts.map(p=>({partId:p.id,x:p.x,y:p.y,width:p.width,height:p.height}))},camera:{framing:'wide',movement:'locked',focus:'ensemble',anchor:{x:640,y:330},startScale:1,endScale:1,designIntent:'Full physical world with seat and floor.'},performance:plan};return {...f,shot};
}
for(const kind of ['stick-man','mini-robot'] as const)for(const facing of ['left','right'] as const){
  test(`${kind}/${facing}: supported sit, same-seat lean hold, stand and walk retain planted feet, fixed bones and real GSAP reverse/random geometry`,()=>{
    const {plan,profile,m}=fixture(kind,facing),compiled=compilePerformance(plan,profile,silence),scene=secureSceneFiles(performanceScene(plan,profile,silence).files),runtime=probe(scene.files.find(f=>f.path==='scene.js')!.content,plan.id);const seat=plan.supports![0]!;
    const times=[0,100,300,499.999,500,500.001,750,900,1400,1800,1950,2080,2300,2800,3199.999,3200,3200.001,3600,4000,5000,5500];const frames=times.map(ms=>samplePerformance(plan,profile,ms,silence));retain(kind+'-'+facing+'-seated',{plan,frames,report:compiled.report});
    for(const frame of frames){bones(frame.transforms,m,.003);if(frame.timeMs<=3600)assert.deepEqual(frame.feet,frames[0]!.feet);if(frame.timeMs>=900&&frame.timeMs<=2800){assert.ok(dist(xy(frame.transforms.pelvis!),seat.center)<.0001);assert.equal(frame.seatContact?.supportId,seat.id);assert.ok(frame.seatContact!.errorPx<.001);}}
    if(facing==='left')for(const side of ['left','right']){const midpoint=samplePerformance(plan,profile,500,silence),hip=xy(midpoint.transforms[`leg-${side}-upper`]!),foot=midpoint.feet[side as 'left'|'right'];assert.ok(Math.abs(dist(hip,foot)-(m.upperLeg+m.lowerLeg))<.001,'pole change must pass through a straight leg');assert.ok(dist(xy(frames[3]!.transforms[`leg-${side}-lower`]!),xy(frames[5]!.transforms[`leg-${side}-lower`!]!))<.1,'straight-leg knee waypoint must not flip');}
    const ids=['pelvis','leg-left-upper','leg-left-lower','leg-right-upper','leg-right-lower','foot-left','foot-right','arm-left-upper','arm-left-lower','hand-left','arm-right-upper','arm-right-lower','hand-right'];for(const ms of [0,499.999,500,500.001,1400,1950,2300,3199.999,3200,3200.001,4000,5500].reverse()){runtime.seek(ms);const actual=Object.fromEntries(ids.map(id=>[id,runtime.attr(id)]));bones(actual,m,.21);const expected=samplePerformance(plan,profile,ms,silence);for(const id of ids)assert.ok(dist(xy(actual[id]!),xy(expected.transforms[id]!))<.21,`seek${ms} changed${id}`);}
    assert.ok(compiled.frames.some(f=>f.timeMs===500));assert.ok(compiled.frames.some(f=>f.timeMs===3200));
  });
  test(`${kind}/${facing}: both seated hands can contact independently while pelvis and feet remain on support`,()=>{
    const {plan,profile,m}=fixture(kind,facing);plan.walks=[];plan.postures=plan.postures!.slice(0,1);const rest=samplePerformance(plan,profile,1400,silence);plan.gestures=(['left','right'] as const).map(hand=>({id:hand+'-inspect',hand,action:'operate' as const,startMs:1000,endMs:2800,contactMs:1300,target:{x:rest.hands[hand].x,y:rest.hands[hand].y-20}}));const compiled=compilePerformance(plan,profile,silence),runtime=probe(secureSceneFiles(performanceScene(plan,profile,silence).files).files.find(f=>f.path==='scene.js')!.content,plan.id);
    for(const ms of [1300,1700,2500,1700]){const frame=samplePerformance(plan,profile,ms,silence);runtime.seek(ms);bones(frame.transforms,m,.003);assert.ok(dist(xy(frame.transforms.pelvis!),plan.supports![0]!.center)<.001);for(const hand of ['left','right'] as const){assert.ok(dist(frame.hands[hand],plan.gestures.find(g=>g.hand===hand)!.target!)<.001);assert.ok(dist(xy(runtime.attr('hand-'+hand)),frame.hands[hand])<.21);}}retain(kind+'-'+facing+'-seated-contact',{plan,report:compiled.report});
  });
  test(`${kind}/${facing}: common cinematic renderer includes the physical support in the same camera world`,()=>{const {shot,profile}=shotFor(kind,facing);assert.doesNotThrow(()=>validateCinematicShot(shot,profile,config));const r=renderCinematic(shot,profile,buildRig(profile),silence,config),files=secureSceneFiles(r.files),html=files.files.find(f=>f.path==='index.html')!.content;assert.ok('seatSupportVersion' in r.report);assert.equal(r.report.seatSupportVersion,'physical-seat-2.2.1');const camera=html.indexOf('class="camera-rig"'),seat=html.indexOf('id="support-seat-inspection-seat"'),performer=html.indexOf('id="performer"');assert.ok(camera>=0&&seat>camera&&performer>camera,'support and performer share camera world');assert.deepEqual(r.report.seatSupports,shot.cinematic!.performance.supports);const root=process.env.ACTING_RUNTIME_EVIDENCE;if(root)for(const f of files.files)writeFileSync(path.join(root,kind+'-'+facing+'-seated-'+f.path),f.content);});
}
for(const problem of ['short-sit','short-stand','short-same-seat-lean','unknown-seat','intensity','wrong-facing','feet-behind','narrow-seat','off-stage','unreachable-seat','duplicate-seat','seat-change','walk-during-sit','turn-while-seated','support-on-stand','nonfinite','old7','old8','old9'] as const)test(`seat validator rejects ${problem}`,()=>{
  const {plan,profile}=fixture('stick-man','right');assert.doesNotThrow(()=>validatePerformance(plan,profile));
  if(problem==='short-sit')plan.postures![0]!.endMs=799;if(problem==='short-stand')plan.postures![2]!.endMs=3499;if(problem==='short-same-seat-lean')plan.postures![1]!.endMs=2079;if(problem==='unknown-seat')plan.postures![0]!.supportId='missing';if(problem==='intensity')plan.postures![0]!.intensity=.9;if(problem==='wrong-facing')plan.facing='left';if(problem==='feet-behind')plan.supports![0]!.center.x=700;if(problem==='narrow-seat')plan.supports![0]!.width=10;if(problem==='off-stage')plan.supports![0]!.center.x=10;if(problem==='unreachable-seat')plan.supports![0]!.center.y=300;if(problem==='duplicate-seat')plan.supports!.push({...plan.supports![0]!});if(problem==='seat-change'){plan.supports!.push({...plan.supports![0]!,id:'other'});plan.postures![1]!.supportId='other';}if(problem==='walk-during-sit')plan.walks[0]!.startMs=800;if(problem==='turn-while-seated')plan.turns=[{startMs:1400,endMs:1800,direction:'left'}];if(problem==='support-on-stand')plan.postures![2]!.supportId='inspection-seat';if(problem==='nonfinite')plan.supports![0]!.center.y=NaN;if(problem==='old7')plan.compilerVersion='performance-2.2.7';if(problem==='old8')plan.compilerVersion='performance-2.2.8';if(problem==='old9')plan.compilerVersion='performance-2.2.9';assert.throws(()=>validatePerformance(plan,profile));
});
test('same-seat lean280ms is valid while sit/stand699ms remain rejected',()=>{const {plan,profile}=fixture('mini-robot','left');assert.doesNotThrow(()=>compilePerformance(plan,profile,silence));const same=structuredClone(plan);same.postures![1]!.endMs=2079;assert.throws(()=>validatePerformance(same,profile),/280/);});
function ensemble(){const {shot,profile}=shotFor('stick-man','right'),support=character('stick-man','assistant'),sp=actorProfile(support),p=structuredClone(shot.cinematic!.performance);p.leadCharacterId=sp.id;p.profileHash=sp.profileHash;p.root={x:950,y:550};p.supports=[{id:'assistant-seat',kind:'seat',center:{x:885,y:480},width:96,facing:'right'}];p.postures=[{startMs:100,endMs:900,pose:'seated',supportId:'assistant-seat'}];p.walks=[];shot.cinematic!.actorScene!.supporting=[{character:support,performance:p,actions:[{type:'idle',startMs:0,endMs:6000,narrationAnchor:'cue'}],speakingSegmentIds:[]}];return {shot,profile};}
test('shared physical stage deduplicates identical seat geometry independent of JSON order/default backHeight',()=>{const {shot}=ensemble(),primary=shot.cinematic!.performance,support=shot.cinematic!.actorScene!.supporting[0]!.performance;const seat=primary.supports![0]!;seat.backHeight=undefined;support.supports!.push({facing:seat.facing,width:seat.width,center:{y:seat.center.y,x:seat.center.x},kind:'seat',id:seat.id,backHeight:0});assert.equal(sameSeatSupport(seat,support.supports![1]),true);assert.equal(sceneSeats(shot).length,2);});
for(const issue of ['stage','ground','changed-geometry','seat-overlap','transition-owner'] as const)test(`ensemble seats reject ${issue}`,()=>{const {shot}=ensemble(),p=shot.cinematic!.performance,other=shot.cinematic!.actorScene!.supporting[0]!.performance;assert.equal(sceneSeats(shot).length,2);if(issue==='stage')other.stage.width=1200;if(issue==='ground')other.stage.groundY=560;if(issue==='changed-geometry')other.supports!.push({...p.supports![0]!,width:98});if(issue==='seat-overlap')other.supports![0]!.center={x:p.supports![0]!.center.x+20,y:p.supports![0]!.center.y};if(issue==='transition-owner'){other.supports=structuredClone(p.supports);other.postures=[{startMs:100,endMs:900,pose:'seated',supportId:p.supports![0]!.id}];}assert.throws(()=>sceneSeats(shot));});
for(const who of ['primary','supporting'] as const)test(`continuous ${who} preserves occupied seat and posture across reordered JSON; mismatches reject`,()=>{
  const {shot}=ensemble();shot.cinematic!.performance.walks=[];shot.cinematic!.performance.postures=shot.cinematic!.performance.postures!.slice(0,1);shot.cinematic!.continuity.exit=shot.cinematic!.performance.root;
  const next=structuredClone(shot);next.id='seated-next';next.startMs=6000;next.endMs=12000;next.cinematic!.actorScene!.continuity='continuous';for(const p of [next.cinematic!.performance,...next.cinematic!.actorScene!.supporting.map(a=>a.performance)]){p.entryPosture={pose:'seated',supportId:p.supports![0]!.id};p.postures=[];p.walks=[];p.supports=p.supports!.map(s=>({facing:s.facing,width:s.width,center:{y:s.center.y,x:s.center.x},id:s.id,kind:s.kind,backHeight:s.backHeight??0}));}
  const board={version:1 as const,shots:[shot,next]};assert.doesNotThrow(()=>validateActorCast(board,narration));const selected=who==='primary'?next.cinematic!.performance:next.cinematic!.actorScene!.supporting[0]!.performance;selected.supports![0]!.center.x++;assert.throws(()=>validateActorCast(board,narration),/seat geometry/);selected.supports![0]!.center.x--;selected.entryPosture={pose:'stand'};assert.throws(()=>validateActorCast(board,narration),/body posture/);next.cinematic!.actorScene!.continuity='cut';assert.doesNotThrow(()=>validateActorCast(board,narration));retain('continuity-'+who,board);
});