import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { HostProfileSchema, HostActions } from '../packages/host/schemas.js';
import { buildRig, hostSvg, hostPreviewSvg, actorPoseSvg } from '../packages/host/rig.js';
import { compileHost, hostProfileFingerprint } from '../packages/host/index.js';
import { compilePerformance, samplePerformance, validatePerformance, type FrameState } from '../packages/animation/compiler.js';
import { rigMetrics } from '../packages/animation/rig.js';
import { ANIMATION_VERSION, STORY_ANIMATION_VERSION, Moods, type Mood, type PerformancePlan } from '../packages/animation/schemas.js';
import { ConfigSchema } from '../packages/core/config.js';
import { hash, writeJson } from '../packages/core/utils.js';
import { ModelRouter } from '../packages/models/registry.js';
import { planCamera, validateCamera } from '../packages/director/camera.js';
import type { Shot } from '../packages/core/schemas.js';
import { validateSceneScript } from '../packages/scenes/security.js';
import { actorSpeech } from '../packages/actors/model.js';
import { CONTINUOUS_ANIMATION_VERSION } from '../packages/animation/schemas.js';

const evidence=process.env.STORY_EMOTIONS_EVIDENCE??mkdtempSync(path.join(tmpdir(),'story-emotions-continuity-'));
const legacy12Evidence=process.env.STORY_EMOTIONS_LEGACY12_EVIDENCE;
const silence={method:'segment-draft' as const,windowMs:20,intervals:[]};
const kinds=['stick-man','mini-robot'] as const;
const ref={kind:'narration' as const,segmentId:'cue',quote:'An illustrative actor reacts.'};
function retain(name:string,data:unknown){if(evidence){mkdirSync(evidence,{recursive:true});writeFileSync(path.join(evidence,name+'.json'),JSON.stringify(data,null,2));}}
function profile(kind:typeof kinds[number]){return HostProfileSchema.parse({id:'emotion-actor',version:1,kind,role:'story-actor',name:'Actor',description:'Independent emotion fixture',appearance:{outline:'#172B36',shell:'#F5F3EC',screen:'#142A36',accent:'#27D8C5',badge:'#F6BD4F',headScale:1,bodyScale:1,strokeWidth:6},actions:[...HostActions],immutable:['identity'],profileHash:'independent-fixture',compilerVersion:'host-svg-2.2.7',sourcePath:'custom.md'});}
function plan(p:ReturnType<typeof profile>,expressions:PerformancePlan['expressions']=[]):PerformancePlan{return {version:22,compilerVersion:ANIMATION_VERSION,id:'emotion-audit',leadCharacterId:p.id,profileHash:p.profileHash,kind:p.kind,durationMs:3000,fps:30,stage:{width:1280,height:720,groundY:550},root:{x:640,y:550},scale:1,walks:[],turns:[],gestures:[],gazes:[],props:[],expressions};}
const nums=(s:string)=>{const n=s.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi);assert.ok(n,s);return n.map(Number);};
const xy=(s:string)=>{const n=nums(s);return {x:n[0]!,y:n[1]!};};
const dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
const near=(a:number,b:number,tol=.001)=>assert.ok(Math.abs(a-b)<=tol,`${a} vs ${b}, tolerance ${tol}`);
function state(f:FrameState){return {face:f.face,head:f.transforms.head,chest:f.transforms.chest};}
function finite(value:unknown){if(typeof value==='number')assert.ok(Number.isFinite(value));else if(typeof value==='string'){assert.doesNotMatch(value,/NaN|Infinity/);for(const n of value.match(/-?\d+(?:\.\d+)?(?:e[+-]?\d+)?/gi)??[])assert.ok(Number.isFinite(Number(n)));}else if(value&&typeof value==='object')for(const v of Object.values(value))finite(v);}
function stateNumbers(f:FrameState){return [...Object.values(f.face).flatMap(v=>Object.values(v).flatMap(x=>typeof x==='number'?[x]:typeof x==='object'?nums(x.transform):[])),...nums(f.transforms.head!),...nums(f.transforms.chest!)];}
function bones(f:Record<string,string>,p:ReturnType<typeof profile>,tol=.003){const m=rigMetrics(p);for(const side of ['left','right'])for(const [a,b,len] of [[`arm-${side}-upper`,`arm-${side}-lower`,m.upperArm],[`arm-${side}-lower`,`hand-${side}`,m.lowerArm],[`leg-${side}-upper`,`leg-${side}-lower`,m.upperLeg],[`leg-${side}-lower`,`foot-${side}`,m.lowerLeg]] as const){const n=nums(f[a]!),r=n[2]!*Math.PI/180;near(dist(xy(f[a]!),xy(f[b]!)),len*n[3]!,tol);assert.ok(dist({x:n[0]!-Math.sin(r)*len*n[3]!,y:n[1]!+Math.cos(r)*len*n[3]!},xy(f[b]!))<=tol,`${a} disconnected`);}}
// Real installed GSAP and AttrPlugin; synthetic targets deliberately have no nodeType,
// so numeric properties test tween timing without claiming browser CSS rendering.
function probe(js:string,id:string){const registered='const tl=gsap.timeline({paused:true});window.__timelines=window.__timelines||{};window.__timelines['+JSON.stringify(id)+']=tl;'+js;assert.deepEqual(validateSceneScript(registered,id),[]);const targets=new Map<string,Record<string,unknown>>();const document={createElement:()=>({style:{}}),documentElement:{},querySelectorAll:(selector:string)=>{let target=targets.get(selector);if(!target){const attrs:Record<string,string>={};target={x:0,y:0,rotation:0,scaleY:1,opacity:1,getAttribute:(key:string)=>attrs[key]??'',setAttribute:(key:string,value:unknown)=>{attrs[key]=String(value);}};targets.set(selector,target);}return [target];}};const context=vm.createContext({window:{document},document,console,setTimeout:()=>0,clearTimeout:()=>{},Date});vm.runInContext(readFileSync(createRequire(import.meta.url).resolve('gsap/dist/gsap.js'),'utf8'),context);vm.runInContext(`var gsap=window.gsap;const tl=gsap.timeline({paused:true});${js};window.auditTimeline=tl;gsap.ticker.sleep();`,context);const tl=context.window.auditTimeline as {seek:(s:number,suppress:boolean)=>void;kill:()=>void};return {seek:(ms:number)=>tl.seek(ms/1000,true),target:(joint:string)=>{const target=targets.get(`[data-composition-id="${id}"] #${joint}`);assert.ok(target,`missing target ${joint}`);return target;},attr:(joint:string)=>{const target=targets.get(`[data-composition-id="${id}"] #${joint}`);assert.ok(target,`missing ${joint}`);return (target.getAttribute as (key:string)=>string)('transform');},close:()=>tl.kill()};}

for(const kind of kinds){
  test(`${kind}: supplemental legacy12 preserves frozen source29 evaluator, bake and emitted GSAP bytes`,{skip:!legacy12Evidence},()=>{
    assert.ok(legacy12Evidence);const p=profile(kind),previous=JSON.parse(readFileSync(path.join(legacy12Evidence,kind+'-gsap.json'),'utf8')) as {q:PerformancePlan;report:{frames:number};records:Array<{ms:number;frame:FrameState}>},moods=JSON.parse(readFileSync(path.join(legacy12Evidence,kind+'-moods.json'),'utf8')) as Array<{version:string;mood:Mood;frame:FrameState}>;
    assert.equal(previous.q.compilerVersion,CONTINUOUS_ANIMATION_VERSION);const activity={...silence,intervals:[{startMs:1500,endMs:1700,level:.6}]},bytes=JSON.stringify(previous.q),compiled=compilePerformance(previous.q,p,activity),oldJs=readFileSync(path.join(legacy12Evidence,kind+'-emitted.js'),'utf8');
    assert.equal(compiled.js,oldJs,'legacy12 must retain exact original emitted GSAP timing and attributes');assert.equal(compiled.frames.length,previous.report.frames,'legacy12 must retain old bake/refinement schedule');assert.equal(JSON.stringify(previous.q),bytes);
    for(const record of previous.records)assert.equal(JSON.stringify(samplePerformance(previous.q,p,record.ms,activity)),JSON.stringify(record.frame),'legacy12 sampled frame changed');
    const current12=moods.filter(row=>row.version===CONTINUOUS_ANIMATION_VERSION);assert.equal(current12.length,16);for(const row of current12){const q={...plan(p,[{startMs:0,endMs:3000,mood:row.mood}]),compilerVersion:CONTINUOUS_ANIMATION_VERSION} as PerformancePlan;assert.equal(JSON.stringify(samplePerformance(q,p,600,silence)),JSON.stringify(row.frame),'legacy12 mood numeric snapshot changed');}
    const runtime=probe(compiled.js,previous.q.id);try{for(const ms of [1200,1270.125,1600.125,600,1270.125]){runtime.seek(ms);if(ms===1270.125)near(Number(runtime.target('brow-left').rotation),7.482977,.000001);}}finally{runtime.close();retain(kind+'-legacy12-preservation',{baselineRoot:legacy12Evidence,version:CONTINUOUS_ANIMATION_VERSION,frames:compiled.frames.length,priorFrames:previous.report.frames,emittedBytesEqual:true,evaluatedMoodSnapshots:current12.length,sampledFrameSnapshots:previous.records.length,planHash:hash(previous.q),emittedHash:hash(compiled.js)});}
  });
  test(`${kind}: real GSAP holds same moods across unordered boundaries; legacy11 resets and reflects frown`,()=>{
    const p=profile(kind);for(const mood of ['happy','sad'] as const){const q=plan(p,[{startMs:1200,endMs:2500,mood},{startMs:200,endMs:1200,mood}]),held=plan(p,[{startMs:200,endMs:2500,mood}]);const a=probe(compilePerformance(q,p,silence).js,q.id),b=probe(compilePerformance(held,p,silence).js,held.id);try{for(const ms of [1199.999,1200,1200.001,600,1200,1340]){a.seek(ms);b.seek(ms);for(const id of Object.keys(samplePerformance(q,p,ms,silence).face))for(const key of ['opacity','scaleY','rotation','x','y'])near(Number(a.target(id)[key]),Number(b.target(id)[key]),.00001);for(const id of ['head','chest','mouth-smile'])assert.equal(a.attr(id),b.attr(id));}}finally{a.close();b.close();}
    const legacy={...q,compilerVersion:STORY_ANIMATION_VERSION} as PerformancePlan,c=compilePerformance(legacy,p,silence),r=probe(c.js,legacy.id);try{for(const ms of [1200,600,1200,1800]){r.seek(ms);const expected=samplePerformance(legacy,p,ms,silence);near(Number(r.target('mouth-smile').opacity),expected.face['mouth-smile']!.opacity!,.00001);const n=nums(r.attr('mouth-smile'));near(n[1]!+18*n[3]!,18,.004);if(ms===1200)near(Number(r.target('mouth-smile').opacity),0);if(ms===600&&mood==='sad')near(n[3]!,-1);}}finally{r.close();}}
  });
  test(`${kind}: emitted short1/50/200ms clips reach exact midpoint anchors and seek backwards`,()=>{
    const p=profile(kind);for(const length of [1,50,200]){const q=plan(p,[{startMs:200,endMs:200+length,mood:'sad'}]),c=compilePerformance(q,p,silence),r=probe(c.js,q.id);try{for(const ms of [200,200+length/2,200+length,200+length/2,200]){r.seek(ms);const f=samplePerformance(q,p,ms,silence);for(const [id,value] of Object.entries(f.face))for(const [key,v] of Object.entries(value)){if(key==='attr'){const a=nums(r.attr(id)),b=nums(value.attr!.transform);a.forEach((n,i)=>near(n,b[i]!, .001));}else near(Number(r.target(id)[key]),v as number,.000002);}finite(Object.fromEntries(Object.keys(f.transforms).map(id=>[id,r.attr(id)])));}}finally{r.close();}}
  });
  test(`${kind}: all 16 moods execute real GSAP at bake anchors and interpolate exactly between them`,()=>{
    const p=profile(kind),diagnostics:unknown[]=[],failures:unknown[]=[];
    for(const mood of Moods){const q=plan(p,[{startMs:200,endMs:1200,mood},{startMs:1200,endMs:2500,mood}]),c=compilePerformance(q,p,silence),runtime=probe(c.js,q.id);try{
      for(const ms of [0,200,270.125,600,1199.999,1200,1200.001,2450.125,2500,3000,600,1270.125,0]){try{runtime.seek(ms);const lo=c.frames.filter(f=>f.timeMs<=ms).at(-1)!,hi=c.frames.find(f=>f.timeMs>ms)??lo,w=hi===lo?0:(ms-lo.timeMs)/(hi.timeMs-lo.timeMs);const actual:Record<string,unknown>={};
        for(const [id,face] of Object.entries(lo.face)){const target=runtime.target(id);for(const [key,value] of Object.entries(face)){if(key==='attr'){const a=nums(face.attr!.transform),b=nums(hi.face[id]!.attr!.transform),n=nums(runtime.attr(id));n.forEach((v,i)=>near(v,a[i]!+(b[i]!-a[i]!)*w,.00005));near(n[1]!+18*n[3]!,18,.004);actual[id]=runtime.attr(id);}else{const a=value as number,b=hi.face[id]![key as 'opacity'] as number;near(Number(target[key]),a+(b-a)*w,.00002);actual[id+'.'+key]=target[key];}}}
        for(const id of ['head','chest']){const a=nums(lo.transforms[id]!),b=nums(hi.transforms[id]!),n=nums(runtime.attr(id));n.forEach((v,i)=>near(v,a[i]!+(b[i]!-a[i]!)*w,.00005));}diagnostics.push({mood,ms,lowerMs:lo.timeMs,upperMs:hi.timeMs,actual});}catch(error){failures.push({mood,ms,error:String(error)});}
      }
    }finally{runtime.close();retain(kind+'-all-mood-gsap',{diagnostics,failures});}}assert.equal(failures.length,0,JSON.stringify(failures));
  });
  test(`${kind}: primary/supporting speech ownership keeps voiceover mouths closed`,()=>{
    const p=profile(kind),q=plan(p,[{startMs:0,endMs:3000,mood:'sad'}]),activity={...silence,intervals:[{startMs:200,endMs:600,level:.8},{startMs:1200,endMs:1800,level:.5}]},narration={mode:'srt' as const,durationMs:3000,words:[],segments:[{id:'first',startMs:0,endMs:1000,text:'First actor.'},{id:'second',startMs:1000,endMs:3000,text:'Second actor.'}]};
    for(const [role,segments] of [['primary',[]],['supporting',[]],['primary-speaking',['first']],['supporting-speaking',['second']]] as const){const owned=actorSpeech(activity,narration,[...segments],0,3000),c=compilePerformance(q,p,owned),runtime=probe(c.js,q.id);try{for(const ms of [400,1400]){runtime.seek(ms);const speaks=owned.intervals.some(i=>ms>=i.startMs&&ms<i.endMs);near(Number(runtime.target('mouth-talk').scaleY),speaks?1+(ms===400?.8:.5)*2.3:.2);near(Number(runtime.target('mouth-talk').opacity),speaks?1:0);}}finally{runtime.close();retain(kind+'-'+role+'-speech',{segments,activity:owned,report:c.report});}}
  });
  test(`${kind}: 16 actual face states and legacy11 frown anchor; preview uses evaluator`,async()=>{
    const p=profile(kind),rows:unknown[]=[];
    for(const version of [ANIMATION_VERSION,STORY_ANIMATION_VERSION] as const){
      const signatures=new Set<string>();
      for(const mood of Moods){const q={...plan(p,[{startMs:0,endMs:3000,mood}]),compilerVersion:version},f=samplePerformance(q,p,600,silence);validatePerformance(q,p);finite(f);bones(f.transforms,p);signatures.add(JSON.stringify(state(f)));rows.push({version,mood,frame:f});
        const mouth=f.face['mouth-smile']!,n=nums(mouth.attr!.transform);near(n[1]!+18*n[3]!,18); // translation + scale * anchor
        if(mood==='sad'){near(mouth.opacity!,1);near(n[3]!,-1);assert.ok(f.face['brow-left']!.rotation!>0);assert.ok(f.face['eye-left']!.scaleY!<1);}
        if(mood==='angry'){assert.ok(n[3]!<0);assert.ok(f.face['brow-left']!.rotation!<0);}
        if(mood==='afraid'){assert.ok(f.face['mouth-round']!.opacity!>.5);assert.ok(f.face['eye-left']!.scaleY!>1);}
        if(mood==='happy'){near(n[3]!,1);near(mouth.opacity!,1);}
        if(version===ANIMATION_VERSION){const svg=actorPoseSvg(p,mood);assert.match(svg,new RegExp(`id="mouth-smile" opacity="${mouth.opacity}" transform="${mouth.attr!.transform.replace(/[()]/g,'\\$&')}"`));}
      }
      assert.equal(signatures.size,16,'every mood must change actual face/head/chest state');
    }
    const svg=hostPreviewSvg(p);for(const mood of Moods)assert.ok(svg.includes(`>${mood}</text>`));
    if(evidence){writeFileSync(path.join(evidence,kind+'-preview.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(path.join(evidence,kind+'-preview.png'));}
    retain(kind+'-moods',rows);
  });
  for(const mood of ['happy','sad'] as const)test(`${kind}/${mood}: contiguous held pose matches unsplit and unordered clocks, legacy resets`,()=>{
    const p=profile(kind),split=plan(p,[{startMs:200,endMs:1200,mood},{startMs:1200,endMs:2500,mood}]),held=plan(p,[{startMs:200,endMs:2500,mood}]),unordered={...split,expressions:[...split.expressions].reverse()},legacy:PerformancePlan={...split,compilerVersion:STORY_ANIMATION_VERSION};const bytes=JSON.stringify(split);
    const times=[1199.999,1200,1200.001,1230.125];for(const time of times){assert.deepEqual(state(samplePerformance(split,p,time,silence)),state(samplePerformance(held,p,time,silence)));assert.deepEqual(samplePerformance(unordered,p,time,silence),samplePerformance(split,p,time,silence));}
    const legacyNumbers=stateNumbers(samplePerformance(legacy,p,1200,silence)),neutralNumbers=stateNumbers(samplePerformance(plan(p),p,1200,silence));legacyNumbers.forEach((v,i)=>near(v,neutralNumbers[i]!,0));assert.notDeepEqual(state(samplePerformance(split,p,1200,silence)),state(samplePerformance(legacy,p,1200,silence)));compilePerformance(split,p,silence);assert.equal(JSON.stringify(split),bytes);
    retain(kind+'-'+mood+'-boundary',{split,held,unordered,legacy,frames:times.map(t=>samplePerformance(split,p,t,silence))});
  });
  for(const [from,to] of [['happy','sad'],['angry','afraid']] as const)test(`${kind}/${from}->${to}: no early cue and continuous direct blend`,()=>{
    const p=profile(kind),q=plan(p,[{startMs:0,endMs:1200,mood:from},{startMs:1200,endMs:2800,mood:to}]),a=plan(p,[{startMs:0,endMs:3000,mood:from}]),b=plan(p,[{startMs:0,endMs:3000,mood:to}]);
    for(const ms of [1000,1199,1199.999,1200])assert.deepEqual(state(samplePerformance(q,p,ms,silence)),state(samplePerformance(a,p,ms,silence)),'future cue appeared early');
    const left=stateNumbers(samplePerformance(q,p,1199.999,silence)),right=stateNumbers(samplePerformance(q,p,1200.001,silence));left.forEach((v,i)=>near(v,right[i]!, .001));assert.deepEqual(state(samplePerformance(q,p,1340,silence)),state(samplePerformance(b,p,1340,silence)));assert.notDeepEqual(state(samplePerformance(q,p,1270,silence)),state(samplePerformance(plan(p),p,1270,silence)));
    retain(kind+'-'+from+'-'+to,{q,frames:[1199.999,1200,1200.001,1270,1340].map(ms=>samplePerformance(q,p,ms,silence))});
  });
  test(`${kind}: gaps recover and 1/50/200ms clips have finite midpoint blend anchors`,()=>{
    const p=profile(kind),q=plan(p,[{startMs:200,endMs:1000,mood:'sad'},{startMs:1200,endMs:2400,mood:'happy'}]),neutral=plan(p);for(const t of [1000,1100,1200,2400,2500])assert.deepEqual(state(samplePerformance(q,p,t,silence)),state(samplePerformance(neutral,p,t,silence)));
    for(const length of [1,50,200]){const short=plan(p,[{startMs:200,endMs:200+length,mood:'sad'}]),compiled=compilePerformance(short,p,silence);assert.ok(compiled.frames.some(f=>f.timeMs===200+length/2));for(const frame of compiled.frames)finite(frame);const peak=samplePerformance(short,p,200+length/2,silence);near(peak.face['mouth-smile']!.opacity!,1);near(nums(peak.face['mouth-smile']!.attr!.transform)[3]!,-1);retain(kind+'-short-'+length,{short,frames:compiled.frames,report:compiled.report});}
  });
  test(`${kind}: emitted GSAP forward/reverse/random seeks interpolate mouth/brows/eyes/head and speech`,()=>{
    const p=profile(kind),q=plan(p,[{startMs:200,endMs:1200,mood:'happy'},{startMs:1200,endMs:2500,mood:'sad'}]),activity={...silence,intervals:[{startMs:1500,endMs:1700,level:.6}]},compiled=compilePerformance(q,p,activity),runtime=probe(compiled.js,q.id);const records:unknown[]=[];
    try{for(const ms of [0,200,270.125,600,1199.999,1200,1200.001,1270.125,1340,1500,1600.125,1700,2450.125,2500,3000,1600.125,1270.125,600,0]){runtime.seek(ms);const f=samplePerformance(q,p,ms,activity),actual:Record<string,unknown>={};for(const [id,face] of Object.entries(f.face)){const target=runtime.target(id);for(const [key,value] of Object.entries(face))if(key==='attr'){const n=nums(runtime.attr(id)),expected=nums(face.attr!.transform);n.forEach((v,i)=>near(v,expected[i]!, .09));near(n[1]!+18*n[3]!,18,.004);actual[id]=runtime.attr(id);}else {try{near(Number(target[key]),value as number,.025);}catch(error){retain(kind+'-temporal-failure',{ms,id,key,actual:target[key],expected:value,tolerance:.025,frame:f,lower:compiled.frames.filter(x=>x.timeMs<=ms).at(-1),upper:compiled.frames.find(x=>x.timeMs>ms)});throw new Error('GSAP '+kind+' time='+ms+' '+id+'.'+key+': '+String(error));}}}
      const transforms=Object.fromEntries(Object.keys(f.transforms).map(id=>[id,runtime.attr(id)]));bones(transforms,p,.21);for(const id of ['head','chest']){const a=nums(transforms[id]!),b=nums(f.transforms[id]!);a.forEach((v,i)=>near(v,b[i]!,i<2?.21:.06));}assert.deepEqual(f.feet,samplePerformance(q,p,0,silence).feet);if(ms===1600.125)assert.ok(Number(runtime.target('mouth-talk').scaleY)>2);if(ms===1700)near(Number(runtime.target('mouth-talk').scaleY),.2);records.push({ms,frame:f,actual});}
      // Independent linear interpolation oracle between actual baked timestamps.
      const ms=1270.125,lo=compiled.frames.filter(f=>f.timeMs<=ms).at(-1)!,hi=compiled.frames.find(f=>f.timeMs>ms)!,w=(ms-lo.timeMs)/(hi.timeMs-lo.timeMs);runtime.seek(ms);for(const id of ['mouth-smile','brow-left','lid-left','eye-left'])for(const key of ['opacity','rotation','scaleY'] as const){const a=lo.face[id]?.[key],b=hi.face[id]?.[key];if(a!==undefined&&b!==undefined)near(Number(runtime.target(id)[key]),a+(b-a)*w,.00001);}
    }finally{runtime.close();retain(kind+'-gsap',{q,report:compiled.report,records});if(evidence)writeFileSync(path.join(evidence,kind+'-emitted.js'),compiled.js);}
  });
  test(`${kind}: emotions preserve dual hand contact, fixed bones and planted feet`,()=>{
    const p=profile(kind),q=plan(p,[{startMs:0,endMs:1200,mood:'angry'},{startMs:1200,endMs:2800,mood:'afraid'}]),rest=samplePerformance(plan(p),p,1000,silence);q.gestures=(['left','right'] as const).map(hand=>({id:hand+'-contact',hand,action:'operate',startMs:300,endMs:2600,contactMs:700,target:{x:rest.hands[hand].x,y:rest.hands[hand].y-20}}));const compiled=compilePerformance(q,p,silence),runtime=probe(compiled.js,q.id);try{for(const ms of [700,1199.999,1200,1270.125,1800]){const f=samplePerformance(q,p,ms,silence);runtime.seek(ms);bones(f.transforms,p);assert.deepEqual(f.feet,rest.feet);for(const hand of ['left','right'] as const){assert.ok(dist(f.hands[hand],q.gestures.find(g=>g.hand===hand)!.target!)<.001);assert.ok(dist(xy(runtime.attr('hand-'+hand)),f.hands[hand])<.21);}assert.ok(f.contactError<.001);}}finally{runtime.close();retain(kind+'-contact',{q,report:compiled.report});}
  });
  test(`${kind}: legacy10 retains physical seat and two hand tracks, rejects story moods`,()=>{
    const p=profile(kind),q=plan(p),m=rigMetrics(p);q.compilerVersion='performance-2.2.10';q.facing='right';q.supports=[{id:'seat',kind:'seat',center:{x:640-m.upperLeg,y:550-m.lowerLeg},width:96,facing:'right',backHeight:65}];q.postures=[{startMs:100,endMs:900,pose:'seated',supportId:'seat'}];const rest=samplePerformance(q,p,1400,silence);q.gestures=(['left','right'] as const).map(hand=>({id:hand+'-seat-contact',hand,action:'operate',startMs:1000,endMs:2800,contactMs:1300,target:{x:rest.hands[hand].x,y:rest.hands[hand].y-20}}));const bytes=JSON.stringify(q);validatePerformance(q,p);const c=compilePerformance(q,p,silence);assert.equal(JSON.stringify(q),bytes);for(const ms of [1300,1700,2400]){const f=samplePerformance(q,p,ms,silence);bones(f.transforms,p);assert.ok(f.seatContact!.errorPx<.001);for(const hand of ['left','right'] as const)assert.ok(dist(f.hands[hand],q.gestures.find(g=>g.hand===hand)!.target!)<.001);}assert.throws(()=>validatePerformance({...q,expressions:[{startMs:0,endMs:3000,mood:'sad'}]},p),/Story emotions require/);retain(kind+'-legacy10',{q,report:c.report});
  });
  test(`${kind}: actor face reaction camera accepts emotions and rejects neutral/crop/hidden contact`,()=>{
    const p=profile(kind);for(const mood of ['sad','happy','angry','afraid'] as const){const q=plan(p,[{startMs:0,endMs:3000,mood}]),shot={id:'camera-audit',camera:{angle:'eye-level'},cinematic:{performance:q,camera:planCamera(q,p,{framing:'close',movement:'locked',focus:'face'}),actorScene:{primary:{id:p.id},supporting:[]}}} as unknown as Shot;assert.doesNotThrow(()=>validateCamera(shot,p));const c=shot.cinematic!;q.expressions=[{startMs:0,endMs:3000,mood:'neutral'}];assert.throws(()=>validateCamera(shot,p),/informative expression/);q.expressions=[{startMs:0,endMs:3000,mood}];c.camera.anchor.x=1200;assert.throws(()=>validateCamera(shot,p),/crops the face/);c.camera=planCamera(q,p,{framing:'close',movement:'locked',focus:'face'});q.gestures=[{id:'hidden',action:'operate',startMs:0,endMs:2800,contactMs:700,target:{x:700,y:400}}];assert.throws(()=>validateCamera(shot,p),/hide contact/);q.gestures=[];delete c.actorScene;assert.throws(()=>validateCamera(shot,p),/informative expression/);}
  });
  test(`${kind}: custom cache preview upgrade invokes no provider and preserves approved bytes`,async()=>{
    assert.ok(evidence,'set STORY_EMOTIONS_EVIDENCE to an outside-repository root');const evidenceRelative=path.relative(process.cwd(),path.resolve(evidence));assert.ok(evidenceRelative.startsWith('..'+path.sep)||path.isAbsolute(evidenceRelative),'evidence must stay outside the repository');const root=path.join(evidence,kind+'-cache');await fs.mkdir(root,{recursive:true});await fs.writeFile(path.join(root,'custom.md'),'# Independent custom actor\ncharacter_kind: '+kind);const p=profile(kind),rig=buildRig(p),config=ConfigSchema.parse({host:{profile:'custom.md'}});for(const [file,data] of [['work/host-profile.json',p],['work/host-rig.json',rig],[rig.posePath,{profileId:p.id,profileVersion:p.version,rigHash:rig.rigHash,poses:rig.poses}],['work/state.json',{approvals:{host:true,hostHash:rig.rigHash},locked:{host:true}}]] as const)await writeJson(path.join(root,file),data);await fs.mkdir(path.dirname(path.join(root,rig.assetPath)),{recursive:true});await fs.writeFile(path.join(root,rig.assetPath),hostSvg(p));await fs.mkdir(path.join(root,'previews'),{recursive:true});await sharp({create:{width:1,height:1,channels:4,background:'#ffffff'}}).png().toFile(path.join(root,'previews/host-preview-sheet.png'));await fs.writeFile(path.join(root,'voice.wav'),'immutable voice sentinel');const inputHash=hash({profile:await hostProfileFingerprint(root,config),id:config.host.profile_id});await writeJson(path.join(root,'work/host-compile-cache.json'),{inputHash,previewVersion:'performance-2.2.9'});const files=['work/host-profile.json','work/host-rig.json',rig.assetPath,rig.posePath,'work/state.json','voice.wav'],before=await Promise.all(files.map(f=>fs.readFile(path.join(root,f))));let calls=0;const router={isMock:()=>false,structured:()=>{calls++;throw new Error('FORBIDDEN provider call');}} as unknown as ModelRouter;const result=await compileHost(root,config,router);assert.equal(calls,0);assert.deepEqual(result,{profile:p,rig});for(const [i,file] of files.entries())assert.deepEqual(await fs.readFile(path.join(root,file)),before[i]);assert.equal(JSON.parse(await fs.readFile(path.join(root,'work/host-compile-cache.json'),'utf8')).previewVersion,ANIMATION_VERSION);const png=await fs.readFile(path.join(root,'previews/host-preview-sheet.png')),expected=await sharp(Buffer.from(hostPreviewSvg(p))).png().toBuffer();assert.deepEqual(png,expected);retain(kind+'-cache-receipt',{calls,files:files.map((file,i)=>({file,sha256:hash(before[i]!)})),rigHash:rig.rigHash,previewHash:hash(png)});
  });
}
