import type {Beat,Narration} from '../core/schemas.js';
import type {HostProfile} from '../host/schemas.js';
import type {ActorDefinition} from '../actors/schemas.js';
import {rigMetrics} from '../animation/rig.js';
import {CAMERA_VIEWPORT} from './camera.js';
import {actingSourceWindows} from './story-coverage.js';
import {nativeClothDescription,hasBodyViewLocomotion} from '../animation/body-view-cloth.js';
import {nativeManipulationDescription,hasBodyViewManipulation} from '../animation/native-contact-arm.js';
import {sourceManipulationDescription} from '../animation/view-source-manipulation.js';
import {sourceSpearDescription} from '../animation/view-source-spear.js';
import {sourceSpearBindingDescription} from './source-spear-bindings.js';
import {sourceSpearActionDescription} from './source-spear-actions.js';
import {sourceSpearInteractionDescription} from './source-spear-interactions.js';
import {modelContactDescription} from './model-contact-motion.js';
import {sourceSpearEmittedDescription} from './source-spear-emitted.js';
import {projectedModelGeometryDescription} from './projected-model-geometry.js';
import {projectedOverlayDescription} from './projected-model-overlays.js';
import {physicalPerformanceDescription} from '../animation/compiler.js';
import {sourceManipulationActionDescription} from './source-manipulation-actions.js';
import {sourcePropBindingDescription} from './source-prop-binding.js';
import {sourceWorldDescription} from './source-world.js';
import {sourceInteractionDescription} from './source-interactions.js';
import {sourceFixedOperationDescription} from './source-fixed-operation.js';
import {sourceGripWorldDescription} from './source-grip-world.js';
import {sourceOwnershipDescription} from './source-ownership.js';
import {ownershipRenderDescription} from './ownership-compile.js';
import {ownershipObservationDescription} from './ownership-scene.js';
import {cameraDirectionDescription} from './camera-direction-schemas.js';
import {castCameraDescription} from './cast-camera.js';
import {cameraRepairDescription} from './camera-repair.js';
import {BODY_SOURCE_VERSION} from '../animation/schemas.js';
import {nativeSecondaryDescription,hasBodyViewSecondary} from '../animation/body-view-secondary.js';
import {nativeSeatDescription,hasBodyViewSeat} from '../animation/body-view-seat.js';
import {nativeHeadBankDescription} from '../animation/native-head-bank.js';
import {hasNativeHeadBank} from '../animation/body-head-bank.js';
import {isNativeHeadFaceVersion} from '../animation/native-head-identity.js';

/** Generation assistance only: no authored choreography, approval or cache identity. */
export function creativeActingBrief(beats:Beat[],narration:Narration,profile:HostProfile,lockedActors:ActorDefinition[]=[]){
  const unitProfile={...profile,appearance:{...profile.appearance,headScale:1,bodyScale:1}};
  return {
    filmRoles:cameraDirectionDescription,
    castCamera:castCameraDescription,cameraRepair:cameraRepairDescription,
    nativeHeadSource:{candidate:nativeHeadBankDescription,selected:hasNativeHeadBank(profile),lockedActors:lockedActors.filter(hasNativeHeadBank).map(a=>a.id),
      explicitSelections:[{actor:profile,scope:'seed-profile'},...lockedActors.map(actor=>({actor,scope:'locked-story-actor'}))].filter(s=>hasNativeHeadBank(s.actor)).map(({actor:a,scope})=>{const bank=a.appearance.bodyHeadBank!;return {scope,actorId:a.id,modelId:bank.actor,bankId:bank.id,version:bank.version,fingerprint:bank.fingerprint,
        sourceFace:isNativeHeadFaceVersion(bank.version),capabilities:bank.capabilities,productionReady:bank.productionReady};}),
      rule:'No accepted production bank exists. Preserve only an explicitly supplied own-model appearance.bodyHeadBank paired with performance.sourceHead; do not select or invent a bank, landmark, yaw or approval. Repeat the identical complete original person-owned source run on every visible continuous camera slice with empty local headTurns. Version1–2 cells have no speech/directional eye capability. Explicit version3 principal or version4 own supporting source-face candidates can provide bounded local mouth/activity and eye/blink controls only when their registered capabilities and original speaker/acting clocks support them. Only explicit version5/6 with complete own face2 registrations adds bounded brow/closed emotional mouth/eye-closure controls on the original actor-expression clock. Supplied version3/4 banks cannot be promoted to version5 or assigned another drawing’s facial ROIs. Version5 may select own paint1 rear partitions; only explicit version6 with complete own paint2/motion enables rear-source texture follow when secondary capability is true, on the complete original head/body history. Version6 with no rear region explicitly retains no secondary capability. Cell changes are blocked pending continuous hair correspondence. Do not promote supplied banks or borrow fixed-body hair masks. None grants phoneme sync, inferred body/head turns or production acceptance. Never borrow principal facial ROIs for quần chúng, reuse held art, mirror/warp/crossfade faces or remove sourced spoken/acting obligations to make an unsupported candidate pass. Report missing source capability; retain all identity/contact/art/voice/final gates.'},
    actorGaze:{selection:'performance.gazes[].actorTarget',shape:{startMs:'shot-local integer ms',endMs:'shot-local integer ms',actorTarget:{id:'exact co-present actor ID',anchor:'eyes'}},
      rule:'A gaze uses either target:{x,y} for a fixed world point OR actorTarget:{id,anchor:eyes}, never both. Actor eye following requires explicitly registered native eyes/body/expression target and native eyes on the looking actor. Resolve the real complete visible target run, root/stage/scale/view, sourceBody support/motion and original expression/breath clock through camera/primary changes. No self/missing/hidden target, source approximation or gaze feedback. Behind the fixed native view still requires matching authored view/turn; this candidate supplies pupil direction only, not head/body turning or optical/production acceptance. Do not replace a sourced turn with pupil movement.'},
    nativeSeating:{candidate:nativeSeatDescription,selected:hasBodyViewSeat(profile),lockedActors:lockedActors.filter(hasBodyViewSeat).map(actor=>actor.id),rule:'Only an explicitly selected registered-seated-v1 native actor/view with registered-locomotion-v1 may sit/hold/rise. Define physical seat supports with matching facing, fixed reachable hips/soles and transitions at least1500ms. One complete shot uses local supports/postures. Camera cuts through a moving or held seated action require identical complete sourceBody.supports/postures/entryPosture on every visible actor slice in the continuous run, with empty local physical tracks. Primary/supporting and speaker changes retain each actor identity, root/view/stage/scale and source clock. Approach/hold/rise reserve a seat for one actor; stand fully before walking/running/jumping or another actor taking that seat. Preserve the original torso/belt/head and common opaque fold surface. Runtime equivalence and art remain unaccepted; never infer coverage, change sourced obligations to narration or claim motion/art/final acceptance.'},
    sourceWorld:sourceWorldDescription,
    projectedModelContact:modelContactDescription,emittedToolObservation:sourceSpearEmittedDescription,projectedRelations:projectedModelGeometryDescription,projectedOverlays:projectedOverlayDescription,
    sourceOwnership:sourceOwnershipDescription,
    ownershipRenderer:ownershipRenderDescription,
    ownershipObservation:ownershipObservationDescription,
    sourceInteraction:sourceInteractionDescription,
    fixedSourceOperation:sourceFixedOperationDescription,
    sourceSpear:{candidate:sourceSpearDescription,modelBinding:sourceSpearBindingDescription,actionProjection:sourceSpearActionDescription,physicalInteraction:sourceSpearInteractionDescription,productionBinding:'PENDING/needs-source-prop-binding. Original body and entry-owned shaft/primary and secondary palms use one complete actor clock7 through camera cuts and lead/support swaps. Explicit actual person/entity/model/evidence and exact native shaft glyph have a source candidate; model centers and unwrapped angles use emitted compiler transforms. Declare hold-tool/thrust-tool with exact original sourceId/trackId/shaftPartId, actual hand, independent entity target and original whole narration cue. Both gripping palms own the shaft; only its actual tip strikes a different entity. Original world reactions use spearContact and contactEffector=spear-tip strictly after the real contact, without contactHands or local re-contact. Later preview distances reference the original strike point and do not claim ongoing contact. This physical candidate is not an accepted production binding or new native tool pose. Do not replace the source with shot-local thrusts, fake pickup/handoff, pointing, mirrored views or approved flags. Emitted target/contact equivalence, moving fixed artwork anchor contracts and actual art/motion/runtime acceptance remain required.'},
    sourceManipulation:{candidate:sourceManipulationDescription,actionProjection:sourceManipulationActionDescription,modelBinding:sourcePropBindingDescription,gripWorld:sourceGripWorldDescription,physicalGeometry:physicalPerformanceDescription,productionBinding:'PENDING/needs-source-prop-binding. Compiler/actor clock7 can evaluate explicit complete sourceManipulation with identical sourceBody and empty local props/contact. Source action schema/projection preserves original gesture reference/hand/cue/clock without fake re-contact; Original person/entity/model/art/cue binding and actual geometry entry/exit have a complete source candidate. Original world phases, source action groups, physical interaction records and acting coverage have source candidates. Fixed center/explicit own authored handle contact/recovery and per-person API continuity now have source candidates. Bound props may use an explicit own authored handle matching their original physical gripOffset. The original person/model share one physical stage/floor. Original transform/reveal/flow history cannot add a second geometry track to a fixed grip or physically bound entity. Full integrated source production audit and runtime/art/film acceptance remain pending. Physical camera/release queries evaluate original body/head/attention geometry, not voice or facial frames. Do not author this as a production workaround, remove its source fields/gates, or replace a sourced cross-cut transport obligation with pointing or a completed local placement.'},
    nativeManipulation:{candidate:nativeManipulationDescription,selected:hasBodyViewManipulation(profile),lockedActors:lockedActors.filter(hasBodyViewManipulation).map(actor=>actor.id),rule:'Explicit bodyManipulation=registered-manipulation-v1 on the actual native actor/view enables candidate inspect/operate/pick-place/carry/drop. Author elbowPole=rest for every contact gesture, exact matching hand/action/source/clock, and reachable actual targets throughout the body motion. Approach/recovery uses C2 joint angles; owned grip uses the actual world/body-relative path. Use separately selected locomotion/seating for moving bodies. Different actors can own different sourced props. No inferred selection, thumb/finger animation, new spear/left-tool pose, shared/sequential handoff or cross-cut prop clock. No art/production/final approval and no pointing substitution.'},
    nativeSecondary:{candidate:nativeSecondaryDescription,selected:hasBodyViewSecondary(profile),lockedActors:lockedActors.filter(hasBodyViewSecondary).map(actor=>actor.id),rule:'Explicit native secondary selection preserves original texture and rigid facial features. Hair/beard regions follow the complete original head/body/expression run, including history before continuous camera cuts. It supplies secondary motion only; do not use it to substitute for a sourced action, turn, seating or contact. Frame the deformed texture bounds and keep every final/art/source/voice gate.'},
    nativeLocomotion:{candidate:nativeClothDescription,selected:hasBodyViewLocomotion(profile),lockedActors:lockedActors.filter(hasBodyViewLocomotion).map(actor=>actor.id),sourceBody:{version:BODY_SOURCE_VERSION,clock:'startMs/endMs are original narration-global run bounds; inner walks/jumps/postures use milliseconds relative to sourceBody.startMs; supports are fixed world geometry',declaration:'Declare the identical complete sourceBody on every camera slice in an explicit actorScene.continuity=continuous run. Each plan keeps the same original root/stage/scale/view and EMPTY local walks/jumps/postures/entryPosture/supports. Camera continuity.entry/exit use the actual original path at this slice, not the original root or final destination. Never infer a source by matching clip IDs or names.'},rule:'Explicit registered-locomotion-v1 uses its detailed3/4 source; registered-profile-locomotion-v1 uses only its own left/right source; registered-rear-locomotion-v1 uses only its own back-left/back-right source. Each supports forward walk/run, jump and unseated stand/crouch/lean with its own garment. Rear keeps the rigid original head and cannot use eyes/mouth/emotion overlays, chin-contact think, source gesture spans, secondary, tools, supportingModel/head-bank or inferred turns. Actor primary/supporting role swaps keep the same original identity and complete body clock. Rest/point and native body react remain separately validated. A full shot-local action remains available; cutting through moving action requires the exact complete original sourceBody clock and every actor slice. No backward gait or continuous body/head turn. Object contact requires the separate explicit nativeManipulation selection; it does not add new spear/left-tool poses. Seating requires the separate explicit nativeSeating selection and original support clock when sliced. Fixed head/body view must match travel direction. This candidate does not approve artwork or remove production/source/voice/final gates; unsupported obligations must be reported, never changed to narration or a pointing substitute.'},
    completeFilm:'Return a complete production design covering every canonical beat through the ending. A capability-conflict placeholder, unsupported reclassification or idle cast is not a repair of a sourced action. Cutaways and regrouped shots remain available when the accepted actors and actions are covered elsewhere in the same source window.',
    obligations:beats.filter(beat=>beat.sceneIntent?.participants.length).map(beat=>({beatId:beat.id,startMs:beat.startMs,endMs:beat.endMs,
      participants:beat.sceneIntent!.participants.map(actor=>({id:actor.id,name:actor.name,role:actor.role,identity:actor.identity})),
      acting:(beat.sceneIntent!.acting??[]).map(acting=>({...acting,sourceWindows:actingSourceWindows(acting,beat,narration)}))})),
    clock:'Narration, beat, host.actions, supporting.actions and visualization.events use global milliseconds. Ordinary performance walk, jump, gesture, gaze, posture and expression uses shot-local milliseconds: local = global - shot.startMs. Optional sourceBody owns complete physical tracks relative to its original global startMs; optional gesture.sourceSpan owns an original global hand window. Those explicit source clocks must remain complete and identical across their continuous run. The decisive contact/release/flight must fall in its verified source window, not merely somewhere in the film. A matching operate-model action uses the same hand and exact gesture start/end/contact after adding shot.startMs, plus that cue id as narrationAnchor.',
    geometry:{units:'Unscaled rig pixels; root and stage coordinates are world pixels. Multiply rig offsets and bone lengths by performance.scale. bodyScale already affects rigMetrics; do not apply it twice.',
      selectedProfile:rigMetrics(profile),unitProportions:rigMetrics(unitProfile),
      lockedActors:lockedActors.map(actor=>({id:actor.id,metrics:rigMetrics({...profile,kind:actor.kind,appearance:actor.appearance})})),
      proportions:'For a newly designed cast, bodyScale scales all unitProportions except headRadius; headScale scales headRadius. Shoulders start at root plus shoulderY/shoulderOffset before posture/facing. Arm maximum reach is upperArm + lowerArm; allow bend and approach rather than stretching bones. Posture, turn and walk change the hand position. These measurements are layout references, not sampled poses or rendered proof.',
      viewport:CAMERA_VIEWPORT,
      camera:'Project actor head (including robot antenna), hands, feet, object bounds and landing/flight envelopes through BOTH camera endpoints. Safe viewport values are fractions of frame dimensions. World ground follows the world camera. Medium/wide ensemble keeps visible actors inside the action viewport; intentional detail crops use their supported face/contact/object focus contract. Reposition the world/camera or use purposeful cuts; do not claim a rendered inspection.'},
    ownership:'A sourced moving model can belong to any visible story actor. propBindings[].ownerId names the actual person ID and selects that actor’s performance.props, gestures, hand, scale and actions; a supporting owner must be explicit. Omission keeps the primary/presenter contract and never guesses a supporting owner. Prop IDs are local to their actual person: the same local name on different people is valid. Each actor/prop tuple binds once; shared relation/effect centers use canonical partId, never a bare prop name. One local model entity binds to one prop and one hand owner for a completed in-shot pickup/carry/drop. Different actors can move separate sourced objects concurrently, without changing the lead or rewriting their story obligations. Model glyphs, labels, foreground, relations, effects, camera envelopes, exits and reports use the real owner’s compiled clock/scale. Canonical sourceOwnership remains a candidate for shared/sequential ownership through cuts. It can coexist with independent original-source entities only after complete canonical and independent validation over connected original runs, including later owners. Canonical aliases and independent entities keep separate drawings/reports and merge their drawn centers; a per-hand canonical mask preserves generic prop palms outside original active intervals. Production still requires complete runtime/art/motion acceptance; missing capabilities must block the action rather than change the story. Native authored-view actors still require their own actual tool/contact registrations; this ownership feature does not grant missing poses, open art/final gates or replace actions with pointing. Preserve sourced roles/actions/targets/clock.',
    coordinates:'visualization.parts and continuity.models use normalized stage fractions, including the exit object center. prop.origin/prop.destination, gesture targets and rig/root positions use stage pixels. artDirection SVG/layers follow their declared projection/coordinateSpace. Model exit continuity is derived from the actual bound destination; supporting actors share that same world exit. Grip destination differs from object center by gripOffset times performer scale.',
    contactGeometry:{handles:'A custom artDirection.models entry may declare handleAnchor:{x,y} as finite fractions 0..1 of the rendered part viewport, (0,0) top-left and (1,1) bottom-right, including any SVG aspect-policy padding. Target anchor=handle resolves that point; center and label retain their existing meaning. Omit handleAnchor to retain the legacy handle at 15% viewport width and 50% height. Choose contact on the actual artwork, not an unrelated label or empty margin.',
      formula:'handle stageX = stage.width * (part.x + (handleAnchor.x - 0.5) * part.width); stageY = stage.height * (part.y + (handleAnchor.y - 0.5) * part.height). This same point drives target validation, host/actor contact and any rendered control. Part positions/dimensions remain normalized stage fractions.',
      grip:'For a moving binding, prop.origin must equal the part center in stage pixels. Initial hand grip = prop.origin + gripOffset * performance.scale; it must equal the resolved action anchor and gesture.target. At release, object destination = gesture.destination - gripOffset * performance.scale. Do not replace the object center with its grip or reuse another actor scale.',
      timing:'A contactRequired event begins strictly AFTER the required actor/hand contactMs, not at the same millisecond. The matching operate-model action must cover the event through event.endMs. Preserve current cue evidence and clock. Check reach across the compiler samples throughout posture/walk/turn/contact; approach with the body or change staging instead of stretching the arm.'},
    source:'The canonical beat sceneIntent remains authoritative. Preserve each participant and every acting kind/operation/movement/targetIds; do not relabel manipulation as unsupported or replace a sourced event with commentary. Use the original cue statement and clock. Visual design, casting appearance, pacing within those windows, cuts, setting, expression and composition are freely designed subject to explicit approvals and renderer capabilities.'
  };
}
