import type {Beat,Narration} from '../core/schemas.js';
import type {HostProfile} from '../host/schemas.js';
import type {ActorDefinition} from '../actors/schemas.js';
import {rigMetrics} from '../animation/rig.js';
import {CAMERA_VIEWPORT} from './camera.js';
import {actingSourceWindows} from './story-coverage.js';
import {nativeClothDescription,hasBodyViewLocomotion} from '../animation/body-view-cloth.js';
import {BODY_SOURCE_VERSION} from '../animation/schemas.js';
import {nativeSecondaryDescription,hasBodyViewSecondary} from '../animation/body-view-secondary.js';
import {nativeSeatDescription,hasBodyViewSeat} from '../animation/body-view-seat.js';
import {nativeHeadBankDescription} from '../animation/native-head-bank.js';
import {hasNativeHeadBank} from '../animation/body-head-bank.js';

/** Generation assistance only: no authored choreography, approval or cache identity. */
export function creativeActingBrief(beats:Beat[],narration:Narration,profile:HostProfile,lockedActors:ActorDefinition[]=[]){
  const unitProfile={...profile,appearance:{...profile.appearance,headScale:1,bodyScale:1}};
  return {
    nativeHeadSource:{candidate:nativeHeadBankDescription,selected:hasNativeHeadBank(profile),lockedActors:lockedActors.filter(hasNativeHeadBank).map(a=>a.id),rule:'No available accepted bank exists. A future explicitly registered V3+ source may select appearance.bodyHeadBank and performance.sourceHead together. Repeat the identical complete original run-owned route on every visible continuous camera slice, with empty local headTurns. Do not invent a bank, landmarks, cell yaw or approval, reuse held V1/V2, mirror, warp or crossfade faces. The current candidate supports painted rest-face cells and physical eye/chin anchors only. Speech, observer directional eyes, emotional face artwork and secondary hair are unsupported and must be reported; never remove spoken/acting obligations to make a silent candidate pass. Full face capabilities, body-turn/costume/painter seams, artwork and video acceptance remain required.'},
    actorGaze:{selection:'performance.gazes[].actorTarget',shape:{startMs:'shot-local integer ms',endMs:'shot-local integer ms',actorTarget:{id:'exact co-present actor ID',anchor:'eyes'}},
      rule:'A gaze uses either target:{x,y} for a fixed world point OR actorTarget:{id,anchor:eyes}, never both. Actor eye following requires explicitly registered native eyes/body/expression target and native eyes on the looking actor. Resolve the real complete visible target run, root/stage/scale/view, sourceBody support/motion and original expression/breath clock through camera/primary changes. No self/missing/hidden target, source approximation or gaze feedback. Behind the fixed native view still requires matching authored view/turn; this candidate supplies pupil direction only, not head/body turning or optical/production acceptance. Do not replace a sourced turn with pupil movement.'},
    nativeSeating:{candidate:nativeSeatDescription,selected:hasBodyViewSeat(profile),lockedActors:lockedActors.filter(hasBodyViewSeat).map(actor=>actor.id),rule:'Only an explicitly selected registered-seated-v1 native actor/view with registered-locomotion-v1 may sit/hold/rise. Define physical seat supports with matching facing, fixed reachable hips/soles and transitions at least1500ms. One complete shot uses local supports/postures. Camera cuts through a moving or held seated action require identical complete sourceBody.supports/postures/entryPosture on every visible actor slice in the continuous run, with empty local physical tracks. Primary/supporting and speaker changes retain each actor identity, root/view/stage/scale and source clock. Approach/hold/rise reserve a seat for one actor; stand fully before walking/running/jumping or another actor taking that seat. Preserve the original torso/belt/head and common opaque fold surface. Runtime equivalence and art remain unaccepted; never infer coverage, change sourced obligations to narration or claim motion/art/final acceptance.'},
    nativeSecondary:{candidate:nativeSecondaryDescription,selected:hasBodyViewSecondary(profile),lockedActors:lockedActors.filter(hasBodyViewSecondary).map(actor=>actor.id),rule:'Explicit native secondary selection preserves original texture and rigid facial features. Hair/beard regions follow the complete original head/body/expression run, including history before continuous camera cuts. It supplies secondary motion only; do not use it to substitute for a sourced action, turn, seating or contact. Frame the deformed texture bounds and keep every final/art/source/voice gate.'},
    nativeLocomotion:{candidate:nativeClothDescription,selected:hasBodyViewLocomotion(profile),lockedActors:lockedActors.filter(hasBodyViewLocomotion).map(actor=>actor.id),sourceBody:{version:BODY_SOURCE_VERSION,clock:'startMs/endMs are original narration-global run bounds; inner walks/jumps/postures use milliseconds relative to sourceBody.startMs; supports are fixed world geometry',declaration:'Declare the identical complete sourceBody on every camera slice in an explicit actorScene.continuity=continuous run. Each plan keeps the same original root/stage/scale/view and EMPTY local walks/jumps/postures/entryPosture/supports. Camera continuity.entry/exit use the actual original path at this slice, not the original root or final destination. Never infer a source by matching clip IDs or names.'},rule:'Only explicitly selected registered-locomotion-v1 native actor/view can use forward walk/run, jump, stand/crouch/lean and point/think/react. A full shot-local action remains available; cutting through moving action requires the exact complete original sourceBody clock and every actor slice. No backward gait, continuous body/head turn or new prop/contact registration. Seating requires the separate explicit nativeSeating selection and original support clock when sliced. Fixed head/body view must match travel direction. This candidate does not approve artwork or remove production/source/voice/final gates; unsupported obligations must be reported, never changed to narration or a pointing substitute.'},
    completeFilm:'Return a complete production design covering every canonical beat through the ending. A capability-conflict placeholder, unsupported reclassification or idle cast is not a repair of a sourced action. Cutaways and regrouped shots remain available when the accepted actors and actions are covered elsewhere in the same source window.',
    obligations:beats.filter(beat=>beat.sceneIntent?.participants.length).map(beat=>({beatId:beat.id,startMs:beat.startMs,endMs:beat.endMs,
      participants:beat.sceneIntent!.participants.map(actor=>({id:actor.id,name:actor.name,role:actor.role,identity:actor.identity})),
      acting:(beat.sceneIntent!.acting??[]).map(acting=>({...acting,sourceWindows:actingSourceWindows(acting,beat,narration)}))})),
    clock:'Narration, beat, host.actions, supporting.actions and visualization.events use global milliseconds. Ordinary performance walk, jump, gesture, gaze, posture and expression uses shot-local milliseconds: local = global - shot.startMs. Optional sourceBody owns complete physical tracks relative to its original global startMs; optional gesture.sourceSpan owns an original global hand window. Those explicit source clocks must remain complete and identical across their continuous run. The decisive contact/release/flight must fall in its verified source window, not merely somewhere in the film. A matching operate-model action uses the same hand and exact gesture start/end/contact after adding shot.startMs, plus that cue id as narrationAnchor.',
    geometry:{units:'Unscaled rig pixels; root and stage coordinates are world pixels. Multiply rig offsets and bone lengths by performance.scale. bodyScale already affects rigMetrics; do not apply it twice.',
      selectedProfile:rigMetrics(profile),unitProportions:rigMetrics(unitProfile),
      lockedActors:lockedActors.map(actor=>({id:actor.id,metrics:rigMetrics({...profile,kind:actor.kind,appearance:actor.appearance})})),
      proportions:'For a newly designed cast, bodyScale scales all unitProportions except headRadius; headScale scales headRadius. Shoulders start at root plus shoulderY/shoulderOffset before posture/facing. Arm maximum reach is upperArm + lowerArm; allow bend and approach rather than stretching bones. Posture, turn and walk change the hand position. These measurements are layout references, not sampled poses or rendered proof.',
      viewport:CAMERA_VIEWPORT,
      camera:'Project actor head (including robot antenna), hands, feet, object bounds and landing/flight envelopes through BOTH camera endpoints. Safe viewport values are fractions of frame dimensions. World ground follows the world camera. Medium/wide ensemble keeps visible actors inside the action viewport; intentional detail crops use their supported face/contact/object focus contract. Reposition the world/camera or use purposeful cuts; do not claim a rendered inspection.'},
    ownership:'A moving bound model is owned by the PRIMARY actor performance and propBindings of that shot. Supporting actors may have their own gestures and fixed-object contacts, but cannot own a primary moving prop. Make the manipulating actor primary in an appropriate shot when needed. Each bound prop supports one completed pickup/carry/drop with exactly one hand owner. Co-present actors and simultaneous independent actions remain possible; sequential pickups/handoffs of the same binding and joint ownership are unsupported. Preserve the original sourced entity and full canonical obligations when changing cuts.',
    coordinates:'visualization.parts and continuity.models use normalized stage fractions, including the exit object center. prop.origin/prop.destination, gesture targets and rig/root positions use stage pixels. artDirection SVG/layers follow their declared projection/coordinateSpace. Model exit continuity is derived from the actual bound destination; supporting actors share that same world exit. Grip destination differs from object center by gripOffset times performer scale.',
    contactGeometry:{handles:'A custom artDirection.models entry may declare handleAnchor:{x,y} as finite fractions 0..1 of the rendered part viewport, (0,0) top-left and (1,1) bottom-right, including any SVG aspect-policy padding. Target anchor=handle resolves that point; center and label retain their existing meaning. Omit handleAnchor to retain the legacy handle at 15% viewport width and 50% height. Choose contact on the actual artwork, not an unrelated label or empty margin.',
      formula:'handle stageX = stage.width * (part.x + (handleAnchor.x - 0.5) * part.width); stageY = stage.height * (part.y + (handleAnchor.y - 0.5) * part.height). This same point drives target validation, host/actor contact and any rendered control. Part positions/dimensions remain normalized stage fractions.',
      grip:'For a moving binding, prop.origin must equal the part center in stage pixels. Initial hand grip = prop.origin + gripOffset * performance.scale; it must equal the resolved action anchor and gesture.target. At release, object destination = gesture.destination - gripOffset * performance.scale. Do not replace the object center with its grip or reuse another actor scale.',
      timing:'A contactRequired event begins strictly AFTER the required actor/hand contactMs, not at the same millisecond. The matching operate-model action must cover the event through event.endMs. Preserve current cue evidence and clock. Check reach across the compiler samples throughout posture/walk/turn/contact; approach with the body or change staging instead of stretching the arm.'},
    source:'The canonical beat sceneIntent remains authoritative. Preserve each participant and every acting kind/operation/movement/targetIds; do not relabel manipulation as unsupported or replace a sourced event with commentary. Use the original cue statement and clock. Visual design, casting appearance, pacing within those windows, cuts, setting, expression and composition are freely designed subject to explicit approvals and renderer capabilities.'
  };
}
