import { z } from 'zod';

export const Id = z.string().max(96).regex(/^[a-zA-Z0-9][a-zA-Z0-9_.-]*$/).refine(value => !['constructor','prototype','__proto__'].includes(value) && !/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(value) && !value.endsWith('.'), 'Reserved identifier');
const Time = z.number().int().nonnegative();
export const SceneTypes = ['historical-reconstruction','character-scene','archival-photo','photo-parallax','map','timeline','technical-cutaway','technical-diagram','exploded-view','process-diagram','factory-process','macro-detail','data-chart','document-highlight','newspaper','quote','kinetic-typography','kinetic-text','ui-demo','schematic','comparison','before-after','object-hero','abstract-transition'] as const;
export const TransitionTypes = ['hard-cut','match-cut','fade','dissolve','crossfade','slide-left','slide-right','wipe'] as const;
export const SourceCharacterSchema = z.object({ id: Id, name: z.string(), description: z.string(), immutableTraits: z.array(z.string()).default([]), mutableTraits: z.array(z.string()).default([]) });
export const StorySchema = z.object({ title: z.string().min(1), genre: z.string().default('documentary'), language: z.string().default('vi'), story: z.string().min(1), purpose: z.string().default(''), style: z.object({ visual: z.string(), era: z.string().default('') }), rules: z.array(z.string()).default([]), characters: z.array(SourceCharacterSchema).default([]), facts: z.array(z.object({ claim: z.string(), type: z.enum(['fact','interpretation','visualization']), source: z.string() })).default([]), chronology: z.array(z.string()).default([]), causalChain: z.array(z.string()).default([]) });
export const SegmentSchema = z.object({ id: Id, startMs: Time, endMs: Time, text: z.string().min(1) }).refine(s => s.endMs > s.startMs, 'endMs must exceed startMs');
export const WordSchema = z.object({ text: z.string(), startMs: Time, endMs: Time });
export const NarrationSchema = z.object({ durationMs: z.number().int().positive(), segments: z.array(SegmentSchema).min(1), words: z.array(WordSchema).default([]), audioPath: z.string().optional(), mode: z.enum(['srt','wav','aligned']) });
export const CharacterSchema = z.object({ id: Id, name: z.string(), identity: z.object({ genderPresentation: z.string().default(''), apparentAge: z.string().default(''), body: z.string().default(''), face: z.string().default(''), hair: z.string().default(''), facialHair: z.string().default('') }), wardrobe: z.object({ default: z.string(), eraRules: z.array(z.string()).default([]) }), immutable: z.array(z.string()), mutable: z.array(z.string()), negativeRules: z.array(z.string()).default([]), referenceAssets: z.array(z.string()).default([]), locked: z.boolean().default(true), versions: z.array(z.object({ id: Id, description: z.string(), assets: z.array(z.string()).default([]) })).default([]), poses: z.record(z.string()).default({}) });
export const CharacterBibleSchema = z.object({ characters: z.array(CharacterSchema), seriesId: z.string().optional() });
export const ChapterSchema = z.object({ id: Id, startMs: Time, endMs: Time, title: z.string(), summary: z.string(), narrativePurpose: z.string(), segmentIds: z.array(Id).min(1) });
export const BeatSchema = z.object({ id: Id, chapterId: Id, startMs: Time, endMs: Time, narrationText: z.string(), meaning: z.string(), visualGoal: z.string(), importance: z.number().min(0).max(1), segmentIds: z.array(Id).min(1) });
export const AssetRequestSchema = z.object({ id: Id, type: z.enum(['character','image','video','diagram','music','sfx','document']), description: z.string(), characterId: Id.optional(), versionId: Id.optional(), pose: z.string().optional(), localPath: z.string().optional(), required: z.boolean().default(false), sourceUrl: z.string().url().optional(), license: z.string().optional() });
export const ShotSchema = z.object({ id: Id, startMs: Time, endMs: Time, beatIds: z.array(Id).min(1), sceneType: z.enum(SceneTypes), subject: z.string(), characters: z.array(Id).default([]), visualDescription: z.string(), camera: z.object({ shotSize: z.string(), movement: z.string(), angle: z.string() }), motion: z.array(z.string()).default([]), transitionIn: z.enum(TransitionTypes).default('hard-cut'), transitionOut: z.enum(TransitionTypes).default('hard-cut'), assetNeeds: z.array(AssetRequestSchema).default([]), textOnScreen: z.string().nullable().default(null), recipeId: z.string().nullable().default(null), renderer: z.literal('hyperframes').default('hyperframes'), locked: z.boolean().default(false), intentionalStatic: z.boolean().default(false), intentionalBlack: z.boolean().default(false), sfx: z.array(z.object({ timeMs: Time, type: z.string(), intensity: z.number().min(0).max(1).default(0.3), assetId: Id.optional() })).default([]) }).refine(s => s.endMs > s.startMs, 'Invalid shot interval');
export const StoryboardSchema = z.object({ shots: z.array(ShotSchema).min(1) });
export const AssetSchema = z.object({ id: Id, type: z.string(), path: z.string(), source: z.enum(['local','user','code','stock','archive','generated','template']), status: z.enum(['approved','missing','pending']), hash: z.string(), requestHash: z.string().optional(), shotIds: z.array(Id).default([]), characterId: Id.optional(), versionId: Id.optional(), pose: z.string().optional(), sourceUrl: z.string().optional(), author: z.string().optional(), license: z.string().optional(), retrievedAt: z.string().optional() });
export const AssetManifestSchema = z.object({ assets: z.array(AssetSchema) });
export const SceneFilesSchema = z.object({ files: z.array(z.object({ path: z.string(), content: z.string() })).min(1), dependencies: z.array(z.string()).default([]), notes: z.array(z.string()).default([]) });
export const ReviewIssueSchema = z.object({ shotId: Id, type: z.string(), severity: z.enum(['low','medium','high']), description: z.string(), repair: z.string() });
export const ReviewSchema = z.object({ pass: z.boolean(), issues: z.array(ReviewIssueSchema), mode: z.enum(['vision','rule-based','combined']).optional(), warnings: z.array(z.string()).default([]) });
export const States = ['NEW','INGESTED','TIMED','ANALYZED','STORYBOARDED','ASSETS_READY','SCENES_READY','DRAFT_RENDERED','REVIEWED','REPAIRED','FINAL_RENDERED','QC_PASSED','DONE'] as const;
export const ProjectStateSchema = z.object({ version: z.literal(1), name: z.string(), state: z.enum(States), updatedAt: z.string(), inputHash: z.string(), assetInputHash: z.string().default(''), artifactHashes: z.record(z.string()).default({}), reviewIteration: z.number().int().nonnegative().default(0), approvals: z.object({ storyboard: z.boolean().default(false), characters: z.boolean().default(false) }).default({}), locked: z.record(z.boolean()).default({}), error: z.string().optional() });
export type Story = z.infer<typeof StorySchema>;
export type Narration = z.infer<typeof NarrationSchema>;
export type CharacterBible = z.infer<typeof CharacterBibleSchema>;
export type Chapter = z.infer<typeof ChapterSchema>;
export type Beat = z.infer<typeof BeatSchema>;
export type Shot = z.infer<typeof ShotSchema>;
export type Storyboard = z.infer<typeof StoryboardSchema>;
export type Asset = z.infer<typeof AssetSchema>;
export type AssetManifest = z.infer<typeof AssetManifestSchema>;
export type SceneFiles = z.infer<typeof SceneFilesSchema>;
export type Review = z.infer<typeof ReviewSchema>;
export type ReviewIssue = z.infer<typeof ReviewIssueSchema>;
export type ProjectState = z.infer<typeof ProjectStateSchema>;
export type ProjectStatus = typeof States[number];
