/** Native PNG ink measurements only; no actor/clock/animation is evaluated. */
import path from 'node:path';
import {promises as fs} from 'node:fs';
import sharp from 'sharp';
import {hash} from '../packages/core/utils.js';
import {bodyViewRegistrations} from '../packages/animation/body-view-art.js';
const root=process.cwd();
const regions={
  lila:{'three-quarter-left':[{roi:[345,275,40,32],seed:[363,290]},{roi:[425,272,55,35],seed:[445,286]}],
    'three-quarter-right':[{roi:[626,248,65,50],seed:[661,269],polygon:[[634,292],[644,274],[662,257],[680,258],[686,266],[678,274],[660,279],[648,288],[639,296]]},{roi:[733,241,50,45],seed:[758,256]}]},
  karo:{'three-quarter-left':[{roi:[305,276,60,50],seed:[336,298]},{roi:[416,276,90,64],seed:[450,304]}],
    'three-quarter-right':[{roi:[476,260,93,77],seed:[522,290]},{roi:[599,260,60,50],seed:[626,278],polygon:[[607,269],[628,266],[643,278],[653,298],[651,306],[637,295],[622,290],[608,287]]}]},
} as const;
const inside=(x:number,y:number,points:readonly (readonly number[])[])=>{let yes=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i]!,b=points[j]!;if((a[1]!>y)!==(b[1]!>y)&&x<(b[0]!-a[0]!)*(y-a[1]!)/(b[1]!-a[1]!)+a[0]!)yes=!yes;}return yes;};
const result:Record<string,Record<string,string[]>>={},measurements:unknown[]=[];
for(const actor of ['lila','karo'] as const){result[actor]={};for(const view of ['three-quarter-left','three-quarter-right'] as const){
  const c=bodyViewRegistrations[actor][view],bytes=await fs.readFile(path.join(root,c.file));if(hash(bytes)!==c.sha256)throw new Error('Native brow source changed: '+c.file);
  const {data,info}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});if(info.width!==c.width||info.height!==c.height)throw new Error('Native brow dimensions changed');
  result[actor]![view]=[];
  for(const [slot,r] of regions[actor][view].entries()){
    const [x0,y0,w,h]=r.roi,marks=new Set<number>();
    for(let y=y0;y<y0+h;y++)for(let x=x0;x<x0+w;x++){if('polygon' in r&&!inside(x+.5,y+.5,r.polygon))continue;const j=(y*info.width+x)*4;if(data[j]!<75&&data[j+1]!<50&&data[j+2]!<35&&data[j+3]!>200)marks.add(y*info.width+x);}
    const components:number[][]=[];while(marks.size){const first=marks.values().next().value!;marks.delete(first);const q=[first];for(let k=0;k<q.length;k++){const at=q[k]!;for(const near of [at-1,at+1,at-info.width,at+info.width])if(marks.delete(near))q.push(near);}components.push(q);}
    const component=components.sort((a,b)=>Math.min(...a.map(at=>(at%info.width-r.seed[0])**2+(Math.floor(at/info.width)-r.seed[1])**2))-Math.min(...b.map(at=>(at%info.width-r.seed[0])**2+(Math.floor(at/info.width)-r.seed[1])**2)))[0];
    if(!component||component.length<30)throw new Error('Native brow component needs manual registration: '+actor+'/'+view+'/'+slot);
    const rows=new Map<number,number[]>();for(const at of component)for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const y=Math.floor(at/info.width)+dy,x=at%info.width+dx;rows.set(y,[...(rows.get(y)??[]),x]);}
    const mask=[...rows].sort(([a],[b])=>a-b).map(([y,xs])=>{const left=Math.min(...xs),right=Math.max(...xs)+1;return `M${left} ${y}H${right}V${y+1}H${left}Z`;}).join('');result[actor]![view]!.push(mask);
    measurements.push({actor,view,screenSlot:slot?'screen-right':'screen-left',source:c.file,sha256:c.sha256,size:[c.width,c.height],roi:r.roi,seed:r.seed,polygon:'polygon' in r?r.polygon:null,inkPixels:component.length,maskHash:hash(mask)});
  }
}}
await fs.writeFile(path.join(root,'packages/animation/body-view-brow-regions.ts'),'/** Measured native brow ink components, dilated2px for antialias edges.\n * Generated by scripts/native-brow-registration.ts; original PNGs untouched. */\nexport const nativeBrowRegions='+JSON.stringify(result,null,2)+' as const;\n');
await fs.writeFile(path.join(root,'docs/topics/reviews/native-brow-registration-v1.json'),JSON.stringify({kind:'static-native-png-ink-measurements',approved:false,animationEvaluated:false,threshold:{rBelow:75,gBelow:50,bBelow:35,alphaAbove:200},dilationPixels:2,measurements},null,2)+'\n');
process.stdout.write('Saved eight native brow region measurements; no performance evaluated.\n');
