import {promises as fs} from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import {findRepoRoot} from '../packages/core/config.js';
import {hash,writeJson,exists} from '../packages/core/utils.js';
import {PREHISTORIC_TOPIC_VERSION,prehistoricReadiness,prehistoricReferences} from '../packages/topics/prehistoric-life.js';
import {nativeManipulationDescription} from '../packages/animation/native-contact-arm.js';
import {sourceManipulationDescription} from '../packages/animation/view-source-manipulation.js';
import {sourceSpearDescription} from '../packages/animation/view-source-spear.js';
import {sourceSpearBindingDescription} from '../packages/director/source-spear-bindings.js';
import {sourceSpearActionDescription} from '../packages/director/source-spear-actions.js';
import {sourceSpearInteractionDescription} from '../packages/director/source-spear-interactions.js';
import {modelContactDescription} from '../packages/director/model-contact-motion.js';
import {sourceSpearEmittedDescription} from '../packages/director/source-spear-emitted.js';
import {projectedModelGeometryDescription} from '../packages/director/projected-model-geometry.js';
import {projectedOverlayDescription} from '../packages/director/projected-model-overlays.js';
import {explicitDialogueDescription} from '../packages/voice/dialogue.js';
import {physicalPerformanceDescription} from '../packages/animation/compiler.js';
import {sourceManipulationActionDescription} from '../packages/director/source-manipulation-actions.js';
import {sourcePropBindingDescription} from '../packages/director/source-prop-binding.js';
import {sourceWorldDescription} from '../packages/director/source-world.js';
import {sourceOwnershipDescription} from '../packages/director/source-ownership.js';
import {sourceProductionAuditDescription} from '../packages/director/source-production-audit.js';
import {sourcePreviewDescription} from '../packages/scenes/source-preview-scope.js';
import {ownershipRenderDescription} from '../packages/director/ownership-compile.js';
import {ownershipObservationDescription} from '../packages/director/ownership-scene.js';
import {sourceInteractionDescription} from '../packages/director/source-interactions.js';
import {sourceFixedOperationDescription} from '../packages/director/source-fixed-operation.js';
import {sourceGripWorldDescription} from '../packages/director/source-grip-world.js';
import {cameraDirectionDescription} from '../packages/director/camera-direction-schemas.js';
import {castCameraDescription} from '../packages/director/cast-camera.js';
import {cameraRepairDescription} from '../packages/director/camera-repair.js';
import {releaseEvidenceDescription} from '../packages/review/evidence-schemas.js';
import {ACTOR_PROP_OWNERSHIP_DESCRIPTION} from '../packages/director/props.js';
import {referenceHeadDescription} from '../packages/animation/forest-head-art.js';
import {referenceBodyDescription} from '../packages/animation/forest-body-art.js';
import {poseArtInventory} from '../packages/topics/pose-art-workbench.js';
import {viewArtInventory,viewArtDescription} from '../packages/topics/view-art-workbench.js';
import {bodyViewDescription} from '../packages/animation/body-view-art.js';
import {bodyViewEyesDescription} from '../packages/animation/body-view-eyes.js';
import {bodyViewMouthDescription} from '../packages/animation/body-view-mouth.js';
import {bodyViewExpressionsDescription} from '../packages/animation/body-view-expressions.js';
import {frontBodyRegistrationDescription} from '../packages/animation/body-view-front-registration.js';
import {obliqueBodyRegistrationDescription} from '../packages/animation/body-view-oblique-registration.js';
import {nativeSeatArtDescription,nativeSeatArtInventory} from '../packages/topics/native-seat-art.js';
import {nativeSeatSurfaceInventory} from '../packages/topics/native-seat-surface-inventory.js';
import {nativeActorGazeDescription} from '../packages/animation/view-gaze-target.js';
import {headTurnArtDescription,headTurnInventory} from '../packages/topics/head-turn-art.js';
import {nativeHeadBankDescription} from '../packages/animation/native-head-bank.js';
import {headCellArtDescription,headCellInventory} from '../packages/topics/head-cell-art.js';
import {prehistoricSupportingDescription,prehistoricSupportingModels} from '../packages/topics/supporting-models.js';
import {supportingHeadDescription} from '../packages/animation/prehistoric-supporting-head.js';
import {HEAD_FACE_CANDIDATES,HEAD_FACE_EXPRESSION_CANDIDATES,HEAD_FACE_LAYERED_CANDIDATES,HEAD_FACE_FOLLOW_CANDIDATES,HEAD_FACE_WORKBENCH_VERSION} from '../packages/topics/head-face-candidates.js';
import {nativeDialogueDescription} from '../packages/topics/native-dialogue-candidates.js';
import {VIEW_SOURCE_GESTURE_PROJECTION_VERSION} from '../packages/animation/view-source-gesture.js';
import {nativeHeadIdentities,NATIVE_SUPPORTING_HEAD_BANK_VERSION,NATIVE_EMOTION_HEAD_BANK_VERSION,NATIVE_MOTION_HEAD_BANK_VERSION} from '../packages/animation/native-head-identity.js';
import {supportingFaceDescription} from '../packages/topics/supporting-face-candidates.js';
import {topicCastNormalizationDescription} from '../packages/topics/cast-appearance.js';

// Inventory existing artwork. Never regenerate or approve the rejected vector pack.
const repo=await findRepoRoot(),dir=path.join(repo,'library/topics/prehistoric-life');
await fs.mkdir(dir,{recursive:true});
async function describe(relative:string) {
  const bytes=await fs.readFile(path.join(repo,relative)),metadata=await sharp(bytes).metadata();
  return {file:relative,sha256:hash(bytes),width:metadata.width,height:metadata.height,hasAlpha:metadata.hasAlpha};
}
const references=await Promise.all(prehistoricReferences.map(async reference=>({...reference,...await describe(`docs/topics/assets/${reference.file}`)})));
const supportingMaterials=await Promise.all(Object.values(prehistoricSupportingModels).map(async model=>{
  const material=JSON.parse(await fs.readFile(path.join(repo,model.file.replace(/\.png$/,'.json')),'utf8')),measured=await describe(model.file);
  if(material.sha256!==model.sha256||measured.sha256!==model.sha256||material.width!==model.width||material.height!==model.height||measured.width!==model.width||measured.height!==model.height||material.model!==model.id||material.approved!==false||material.registered!==false||material.productionReady!==false||material.motionVerified!==false)throw new Error('Supporting actor source metadata changed');
  return {...model,...measured,approved:false,registered:false,productionReady:false,motionVerified:false};
}));
const candidates=await Promise.all(['lila','karo'].flatMap(id=>[
  {file:`${id}-cutout-v1.png`,kind:'full-body-cutout',status:'candidate',approved:false,source:`reference-${id}-full.png`},
  {file:`${id}-parts-candidate-v1.png`,kind:'puppet-parts-atlas',status:id==='karo'?'needs-repair-static-vision-review':'candidate-needs-layout-and-fidelity-review',approved:false,source:`reference-${id}-full.png`},
]).map(async asset=>({...asset,...await describe(`library/topics/prehistoric-life/${asset.file}`)})));
const rejected=[];
for(const file of ['colors-day.png','colors-sunset.png','colors-night.png','lila-views.png','karo-views.png','lila-expressions.png','karo-expressions.png']) {
  if(await exists(path.join(dir,file)))rejected.push({...await describe(`library/topics/prehistoric-life/${file}`),status:'rejected-vector-v0.3',productionAllowed:false});
}
const headPack=referenceHeadDescription();
const poseStudies=await poseArtInventory(repo);
const poseEvidence=await Promise.all(poseStudies.map(async study=>{
  const measured=await describe(`library/topics/prehistoric-life/pose-studies/${study.file}`);
  if(measured.sha256!==study.sha256)throw new Error('Pose artwork changed: '+study.file);
  return {...study,...measured,productionAllowed:false};
}));
const viewStudies=await viewArtInventory(repo);
const viewEvidence=await Promise.all(viewStudies.map(async study=>{
  const measured=await describe(`library/topics/prehistoric-life/body-views/${study.file}`);
  if(measured.sha256!==study.sha256||measured.width!==study.width||measured.height!==study.height)throw new Error('Authored view metadata changed: '+study.file);
  return {...study,...measured,productionAllowed:false};
}));
const nativeSeatedMaterials=await nativeSeatArtInventory(repo);
const nativeHeadTurnMaterials=await headTurnInventory(repo);
const nativeHeadCellMaterials=await headCellInventory(repo);
// Read static definition bytes only; do not evaluate a compiler, face state,
// geometry schema or registration while inventorying authoring artifacts.
const nativeFaceDefinitions=await Promise.all([...HEAD_FACE_CANDIDATES,...HEAD_FACE_EXPRESSION_CANDIDATES,...HEAD_FACE_LAYERED_CANDIDATES,...HEAD_FACE_FOLLOW_CANDIDATES].map(async entry=>{
  const {actor,view,id,file,headFile}=entry,identity=nativeHeadIdentities[actor];
  const bytes=await fs.readFile(path.join(repo,file)),definition=JSON.parse(bytes.toString('utf8'));
  if(definition.actor!==actor||definition.id!==id||definition.bodyViews.length!==1||definition.bodyViews[0].view!==view||definition.source.file!=='library/topics/prehistoric-life/head-cells/'+headFile)throw new Error('Face definition catalog/body view differs');
  const follow=HEAD_FACE_FOLLOW_CANDIDATES.some(c=>c.id===id),layered=follow||HEAD_FACE_LAYERED_CANDIDATES.some(c=>c.id===id),emotions=layered||HEAD_FACE_EXPRESSION_CANDIDATES.some(c=>c.id===id);
  if(definition.cells.some((c:{paint?:unknown})=>!!c.paint)!==layered)throw new Error('Static source paint differs from its explicit catalog');
  if(definition.version!==(follow?NATIVE_MOTION_HEAD_BANK_VERSION:emotions?NATIVE_EMOTION_HEAD_BANK_VERSION:identity.supporting?NATIVE_SUPPORTING_HEAD_BANK_VERSION:'native-head-bank-3')||definition.primary.file!==identity.primary.file||definition.primary.sha256!==identity.primary.sha256||definition.approved!==false||definition.productionReady!==false||definition.motionVerified!==false)throw new Error('Face definition model/version/readiness differs');
  if('sha256' in entry&&(definition.source.sha256!==entry.sha256||definition.source.width!==entry.width||definition.source.height!==entry.height))throw new Error('Supporting head source differs from current catalog');
  const primary=await describe(identity.primary.file);if(primary.sha256!==identity.primary.sha256)throw new Error('Face primary image changed');
  const sources=await Promise.all([definition.source,...(definition.additionalSources??[])].map(async(source:{file:string;sha256:string;width:number;height:number})=>{
    if(!/^library\/topics\/prehistoric-life\/(?:head-cells|head-face-plates)\/(?:lila|karo|prehistoric-male-bald|prehistoric-female-haired)-head-[a-z0-9-]+-v[1-9]\d*\.png$/.test(source.file)||!source.file.split('/').at(-1)!.startsWith(actor+'-head-'))throw new Error('Unknown face definition static source');
    const measured=await describe(source.file);if(measured.sha256!==source.sha256||measured.width!==source.width||measured.height!==source.height||!measured.hasAlpha)throw new Error('Face definition raw source differs');return measured;
  }));
  return {actor,view,file,sha256:hash(bytes),primary,bodyTemplate:identity.bodyTemplate,sources,...(layered?{paint:definition.cells.map((c:{paint:unknown})=>c.paint)}:{}),status:'unvalidated-engineering-definition',geometryValidation:'NOT RUN',selected:false,registered:false,approved:false,productionReady:false,motionVerified:false};
}));
const nativeSeatedSurface=await nativeSeatSurfaceInventory(repo);
const headReviewFile='docs/topics/reviews/front-head-static-review-v2.json';
const headReview=await fs.readFile(path.join(repo,headReviewFile),'utf8').then(text=>JSON.parse(text) as {scope:string;appliesTo:string;headPackFingerprint:string;result:{pass:boolean}}).catch(()=>undefined);
const headReviewCurrent=headReview?.headPackFingerprint===headPack.fingerprint;
const projectionReviewFile='docs/topics/reviews/source-head-projection-static-review-v1.json';
const projectionReview=await fs.readFile(path.join(repo,projectionReviewFile),'utf8').then(text=>JSON.parse(text) as {scope:string;appliesTo:string;headPackFingerprint:string;result:{pass:boolean}}).catch(()=>undefined);
const projectionReviewCurrent=projectionReview?.headPackFingerprint===headPack.fingerprint;
const bodyPack=referenceBodyDescription(),bodyReviewFile='docs/topics/reviews/source-waist-static-review-v1.json';
const bodyReview=await fs.readFile(path.join(repo,bodyReviewFile),'utf8').then(text=>JSON.parse(text) as {scope:string;appliesTo:string;bodyPackFingerprint:string;result:{pass:boolean}}).catch(()=>undefined);
const bodyReviewCurrent=bodyReview?.bodyPackFingerprint===bodyPack.fingerprint;
const headCandidates=await Promise.all(Object.entries(headPack.assets).flatMap(([actor,views])=>Object.entries(views).map(async([view,asset])=>{
  const measured=await describe(`library/topics/prehistoric-life/rig-v1/${asset.file}`);
  if(measured.sha256!==asset.sha256||measured.width!==asset.width||measured.height!==asset.height||!measured.hasAlpha)throw new Error(`Head asset metadata changed: ${asset.file}`);
  return {...measured,actor,view,approved:false,status:'candidate-layered-head'};
})));
const garmentCandidates=await Promise.all(Object.entries(bodyPack.seatedGarments.assets).map(async([actor,asset])=>{
  const measured=await describe(asset.file);
  if(measured.sha256!==asset.sha256||measured.width!==asset.width||measured.height!==asset.height||!measured.hasAlpha)throw new Error('Seated garment metadata changed: '+asset.file);
  return {...measured,actor,approved:false,status:'candidate-authored-seated-folds'};
}));
await writeJson(path.join(dir,'manifest.json'),{version:PREHISTORIC_TOPIC_VERSION,...prehistoricReadiness,
  releaseEvidence:{...releaseEvidenceDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/review/evidence-schemas.ts','packages/review/evidence.ts','packages/review/index.ts','packages/orchestrator/pipeline.ts','packages/qc/index.ts','apps/server/artifacts.ts','library/schemas/index.ts','scripts/dev-nine-router.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceGripWorld:{...sourceGripWorldDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/source-grip-world.ts","packages/director/source-prop-binding.ts","packages/director/source-fixed-operation.ts","packages/director/source-actor.ts","packages/director/source-world-projection.ts","packages/director/source-world-phase.ts","packages/director/camera.ts","packages/director/creative.ts","packages/review/index.ts","packages/director/source-prop-identity.ts","packages/director/acting-brief.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  castCamera:{...castCameraDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/cast-camera.ts","packages/director/camera.ts","packages/director/creative.ts","packages/review/index.ts","packages/director/acting-brief.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  cameraRepair:{...cameraRepairDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/camera-repair.ts","packages/director/camera-repair-source.ts","packages/actors/speech-clock.ts","packages/director/camera-direction.ts","packages/director/index.ts","packages/director/artwork-repair.ts","packages/orchestrator/pipeline.ts","packages/review/index.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  filmAgents:{...cameraDirectionDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/camera-direction-report.ts","packages/director/index.ts","packages/director/artwork-repair.ts","packages/director/camera-direction.ts","packages/director/camera-direction-schemas.ts","library/prompts/camera-director.md","library/prompts/creative-director.md","packages/director/creative.ts","packages/director/acting-brief.ts","packages/core/config.ts","packages/story/planning-cache.ts","packages/orchestrator/settings.ts","packages/orchestrator/pipeline.ts","apps/server/contracts.ts","apps/server/index.ts","apps/studio/src/main.ts","packages/director/schemas.ts","library/schemas/index.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceInteractions:{...sourceInteractionDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-interactions.ts','packages/director/source-actor.ts','packages/director/source-fixed-operation.ts','packages/director/source-action-clock.ts','packages/director/source-manipulation-actions.ts','apps/studio/src/cinematic.ts','packages/director/actions.ts','packages/director/story-coverage.ts','packages/director/index.ts','packages/director/schemas.ts','packages/director/acting-brief.ts','packages/host/controller.ts','packages/explainer/storyboard.ts','packages/review/index.ts','library/shots/cinematic.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  fixedSourceOperations:{...sourceFixedOperationDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-fixed-operation.ts','packages/director/source-actor.ts','packages/director/continuity.ts','packages/director/source-world-projection.ts','packages/director/source-world-phase.ts','packages/animation/compiler.ts','packages/actors/model.ts','apps/server/cinematic.ts','packages/host/schemas.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceWorldTimeline:{...sourceWorldDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/source-world-reference.ts","packages/director/source-world-schemas.ts","packages/director/source-world-projection.ts","packages/director/source-world.ts","packages/director/source-world-phase.ts","library/shots/source-world-timeline.ts","library/shots/cinematic-models.ts","library/shots/cinematic.ts","packages/explainer/schemas.ts","packages/actors/speech-clock.ts","packages/scenes/index.ts","packages/scenes/source-publication.ts","packages/director/artwork-repair.ts","packages/director/schemas.ts","packages/director/props.ts","packages/director/index.ts","packages/director/acting-brief.ts","library/schemas/index.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  projectedModelContact:{...modelContactDescription,handoff:'docs/topics/EMITTED-CONTACT-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/director/model-contact-reference.ts','packages/director/model-contact-motion.ts','packages/director/art-direction-schemas.ts','packages/director/art-direction.ts','packages/animation/svg-transform-track.ts','packages/director/source-fixed-operation.ts','packages/director/source-interactions.ts','packages/director/source-spear-interactions.ts','packages/director/source-world.ts','packages/director/camera.ts','packages/host/controller.ts','library/shots/source-world-timeline.ts','library/shots/cinematic.ts','packages/scenes/index.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  projectedRelations:{...projectedModelGeometryDescription,handoff:'docs/topics/PROJECTED-RELATIONS-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/director/projected-model-geometry.ts','packages/director/projected-relation-track.ts','packages/director/model-contact-motion.ts','packages/animation/svg-transform-track.ts','library/shots/projected-relations.ts','library/shots/cinematic-models.ts','library/shots/cinematic.ts','packages/scenes/index.ts','packages/director/acting-brief.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  explicitDialogue:{...explicitDialogueDescription,handoff:'docs/topics/EXPLICIT-DIALOGUE-VOICES-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/voice/dialogue.ts","packages/voice/index.ts","packages/voice/schemas.ts","packages/core/config.ts","packages/core/schemas.ts","packages/ingest/script.ts","packages/actors/explicit-speakers.ts","packages/actors/speech-clock.ts","packages/storyboard/validate.ts","packages/orchestrator/script-generation.ts","packages/orchestrator/pipeline.ts","packages/orchestrator/settings.ts","apps/server/index.ts","apps/server/artifacts.ts","apps/cli/index.ts","apps/studio/src/main.ts","apps/studio/src/api.ts","library/prompts/dialogue-script-writer.md","library/prompts/creative-director.md","packages/actors/model.ts","packages/explainer/plan.ts","library/prompts/character-bible.md","library/prompts/story-analyst.md"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  projectedOverlays:{...projectedOverlayDescription,handoff:'docs/topics/PROJECTED-OVERLAYS-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/director/projected-model-overlays.ts","packages/director/model-decorations.ts","packages/director/model-label.ts","packages/director/projected-model-geometry.ts","packages/director/projected-relation-track.ts","packages/director/model-contact-motion.ts","packages/director/art-direction.ts","packages/director/camera.ts","library/shots/cinematic.ts","library/shots/ownership-layer.ts","library/shots/source-world-timeline.ts","packages/scenes/index.ts","packages/director/acting-brief.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  emittedSpearObservation:{...sourceSpearEmittedDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-spear-emitted.ts','packages/animation/svg-transform-track.ts','library/shots/cinematic.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceSpearActions:{...sourceSpearActionDescription,interaction:sourceSpearInteractionDescription,handoff:'docs/topics/ORIGINAL-SPEAR-ACTIONS-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-spear-action-reference.ts','packages/director/source-spear-action-clock.ts','packages/director/source-spear-actions.ts','packages/director/source-spear-interactions.ts','apps/studio/src/cinematic.ts','packages/director/camera.ts','packages/director/source-spear-bindings.ts','packages/director/source-world-schemas.ts','packages/director/source-world-projection.ts','packages/director/source-world.ts','packages/director/source-world-phase.ts','packages/director/actions.ts','packages/director/source-interactions.ts','packages/director/story-coverage.ts','packages/director/source-production-audit.ts','packages/director/index.ts','packages/director/acting-brief.ts','packages/host/schemas.ts','packages/host/controller.ts','packages/explainer/schemas.ts','packages/explainer/plan.ts','library/shots/cinematic.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceSpearBinding:{...sourceSpearBindingDescription,handoff:'docs/topics/ORIGINAL-SPEAR-MODEL-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-spear-binding-schemas.ts','packages/director/source-spear-bindings.ts','packages/director/source-prop-binding.ts','packages/director/source-prop-identity.ts','packages/director/ownership-bindings.ts','packages/director/ownership-binding-context.ts','packages/director/source-production-audit.ts','packages/director/prop-motion.ts','packages/director/camera.ts','packages/director/props.ts','packages/director/schemas.ts','library/shots/cinematic.ts','library/shots/cinematic-models.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourcePropBinding:{...sourcePropBindingDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/ownership-bindings.ts","packages/director/ownership-binding-context.ts",'packages/director/source-prop-binding.ts','packages/director/source-prop-identity.ts','packages/director/prop-owner.ts','packages/director/props.ts','packages/director/index.ts','packages/director/schemas.ts','packages/director/creative.ts','packages/director/acting-brief.ts','packages/actors/speech-clock.ts','packages/explainer/storyboard.ts','packages/storyboard/director.ts','apps/server/cinematic.ts','apps/server/artifacts.ts','library/shots/cinematic.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceSpear:{...sourceSpearDescription,handoff:'docs/topics/ORIGINAL-SPEAR-CLOCK-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/animation/view-source-spear.ts','packages/animation/schemas.ts','packages/animation/compiler.ts','packages/animation/view-source-body.ts','packages/animation/view-source-manipulation.ts','packages/animation/view-acting-clock.ts','packages/animation/view-gaze-target.ts','packages/actors/view-acting-clock.ts','packages/actors/model.ts','packages/director/camera.ts','packages/director/props.ts','packages/director/index.ts','packages/director/source-audit-context.ts','packages/director/acting-repair.ts','packages/director/acting-brief.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceCinematicPreview:{...sourcePreviewDescription,handoff:'docs/topics/ORIGINAL-SOURCE-PREVIEW-HANDOFF.md',command:'npm run source:preview -- --project <absolute original project> --shot <original shot ID>',codeHashes:Object.fromEntries(await Promise.all(["packages/scenes/source-preview-scope.ts","packages/scenes/source-preview-project.ts","scripts/source-preview.ts","library/shots/cinematic.ts","packages/scenes/security.ts","packages/director/source-audit-context.ts","packages/director/source-production-audit.ts","packages/director/index.ts","packages/actors/rig-resources.ts","packages/animation/forest-head-art.ts","packages/animation/forest-body-art.ts","tests/original-source-preview.test.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceProductionAudit:{...sourceProductionAuditDescription,handoff:'docs/topics/ORIGINAL-SOURCE-AUDIT-HANDOFF.md',endpoint:'GET /api/projects/:name/source-audit',codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-audit-context.ts','packages/director/source-production-audit.ts','packages/director/index.ts','packages/explainer/storyboard.ts','packages/director/props.ts','packages/director/source-world.ts','packages/director/source-prop-binding.ts','packages/director/source-ownership.ts','packages/director/story-coverage.ts','packages/director/cast-camera.ts','apps/server/source-audit.ts','apps/server/index.ts','apps/server/contracts.ts','apps/studio/src/api.ts','apps/studio/src/source-audit.ts','apps/studio/src/main.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceOwnership:{...sourceOwnershipDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-ownership-schemas.ts','packages/director/source-ownership-projection.ts','packages/director/source-ownership.ts','packages/director/source-prop-identity.ts','packages/director/props.ts','packages/director/schemas.ts','packages/director/acting-brief.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  ownershipObservation:{...ownershipObservationDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/ownership-bake-query.ts','packages/director/ownership-render-version.ts','packages/director/ownership-scene.ts','packages/director/ownership-interactions.ts','packages/director/source-interaction-version.ts','packages/director/source-interactions.ts','packages/director/source-prop-identity.ts','packages/director/ownership-compile.ts','packages/director/camera.ts','packages/director/cast-camera.ts','packages/director/camera-repair.ts','packages/director/props.ts','packages/director/index.ts','packages/director/story-coverage.ts','packages/director/creative.ts','packages/director/acting-brief.ts','packages/explainer/storyboard.ts','packages/storyboard/director.ts','packages/review/index.ts','apps/server/cinematic.ts','library/shots/cinematic.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  ownershipRenderer:{...ownershipRenderDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/director/ownership-bindings.ts","packages/director/ownership-binding-context.ts","packages/director/ownership-palm-mask.ts","packages/director/prop-motion.ts","packages/director/ownership-bake-query.ts","packages/director/ownership-render-version.ts",'packages/director/ownership-bake.ts','packages/director/ownership-compile.ts','packages/director/ownership-paint-schemas.ts','packages/director/ownership-reference.ts','library/shots/ownership-layer.ts','library/shots/cinematic.ts','library/shots/source-world-timeline.ts','library/shots/cinematic-models.ts','packages/scenes/index.ts','packages/director/acting-brief.ts','packages/director/schemas.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  physicalGeometry:{...physicalPerformanceDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/animation/compiler.ts','packages/director/camera.ts','packages/animation/forest-body-art.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceManipulationActions:{...sourceManipulationActionDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/director/source-manipulation-actions.ts','packages/director/index.ts','packages/director/schemas.ts','packages/host/schemas.ts','packages/director/acting-repair.ts','packages/director/acting-brief.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  actorPropOwnership:{...ACTOR_PROP_OWNERSHIP_DESCRIPTION,codeHashes:Object.fromEntries(await Promise.all(["packages/director/ownership-bindings.ts","packages/director/ownership-binding-context.ts",'packages/director/props.ts','packages/director/prop-owner.ts','packages/director/prop-motion.ts','packages/director/camera.ts','packages/director/index.ts','packages/director/schemas.ts','packages/director/acting-brief.ts','library/shots/cinematic.ts','library/shots/cinematic-models.ts','library/prompts/creative-director.md','apps/server/cinematic.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  sourceManipulation:{...sourceManipulationDescription,productionBinding:'needs-source-prop-binding',codeHashes:Object.fromEntries(await Promise.all(['packages/animation/view-source-manipulation.ts','packages/animation/schemas.ts','packages/animation/compiler.ts','packages/animation/view-source-body.ts','packages/animation/view-acting-clock.ts','packages/animation/native-contact-arm.ts','packages/animation/scene.ts','packages/actors/view-acting-clock.ts','packages/director/acting-repair.ts','packages/director/acting-brief.ts','packages/director/camera.ts','packages/director/props.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeManipulation:{...nativeManipulationDescription,codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts",'packages/animation/native-contact-arm.ts','packages/animation/compiler.ts','packages/animation/source-arm.ts','packages/animation/rig.ts','packages/animation/scene.ts','packages/animation/body-view-art.ts','packages/animation/forest-body-art.ts','packages/host/schemas.ts','packages/topics/cast-appearance.ts','packages/topics/body-workbench.ts','packages/topics/prehistoric-life.ts','packages/director/acting-brief.ts','packages/director/schemas.ts','library/shots/cinematic.ts','library/shots/cinematic-models.ts','library/prompts/creative-director.md','apps/server/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  castNormalization:{...topicCastNormalizationDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/topics/cast-appearance.ts','packages/topics/prehistoric-life.ts','packages/director/acting-brief.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  primaryModel:'warm-skin-close-ups',referencePolicy:'Supplemental detailed and white-face sheets do not replace or blend into the primary model.',
  supportingCast:{...prehistoricSupportingDescription,materials:supportingMaterials,headCandidate:supportingHeadDescription,nativeFaces:supportingFaceDescription,
    codeHashes:Object.fromEntries(await Promise.all(['packages/topics/supporting-models.ts','packages/topics/supporting-workbench.ts','packages/topics/supporting-face-candidates.ts','packages/topics/prehistoric-life.ts','packages/animation/prehistoric-supporting-head.ts','packages/animation/native-head-identity.ts','packages/actors/design.ts','packages/host/schemas.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))]))),workbench:'/api/topics/prehistoric-life/supporting-actors'},
  nativeSeatedMaterials:{...nativeSeatArtDescription,materials:nativeSeatedMaterials,codeHash:hash(await fs.readFile(path.join(repo,'packages/topics/native-seat-art.ts')))},
  nativeSeatedSurface,
  nativeHeadTurnStudies:{...headTurnArtDescription,materials:nativeHeadTurnMaterials,fingerprint:hash(nativeHeadTurnMaterials),codeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-turn-art.ts'))),landmarkCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-turn-landmarks.ts'))),schemaCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-turn-schemas.ts'))),workbenchCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-turn-workbench.ts')))},
  nativeHeadBank:{...nativeHeadBankDescription,codeHashes:Object.fromEntries(await Promise.all(['packages/animation/native-head-bank.ts','packages/animation/native-head-identity.ts','packages/animation/native-head-track.ts','packages/animation/body-head-bank.ts','packages/animation/native-head-resources.ts','packages/animation/native-head-face.ts','packages/animation/native-head-paint.ts','packages/animation/native-head-follow.ts','packages/core/json-sha256.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeHeadFaces:{version:'native-head-face-2',definitions:nativeFaceDefinitions,selection:'explicit bank3 principal, bank4 supporting, bank5 own emotions/paint or bank6 rear-source follow only after user-model geometry/runtime review; no automatic selection',sourcePaint:{version:'native-head-paint-2',versions:['native-head-paint-1','native-head-paint-2'],handoff:'docs/topics/NATIVE-SOURCE-HEAD-PAINT.md',geometryValidation:'NOT RUN',visualAcceptance:false,secondaryMotion:'explicit bank6 only, own rear regions required; NOT VERIFIED',followHandoff:'docs/topics/NATIVE-SOURCE-HEAD-FOLLOW.md',neckTrim:false},availableBanks:[],productionReady:false,approved:false,motionVerified:false,handoff:'docs/topics/NATIVE-SOURCE-FACE-EMOTIONS.md',
    inspection:{version:HEAD_FACE_WORKBENCH_VERSION,url:'/api/topics/prehistoric-life/head-faces',codeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-face-workbench.ts'))),catalogCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-face-candidates.ts'))),sourceLoaderCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-face-source.ts'))),handoff:'docs/topics/HEAD-FACE-WORKBENCH.md',runtimeVerified:false,audioPresent:false,productionReady:false}},
  nativeHeadCells:{...headCellArtDescription,materials:nativeHeadCellMaterials,fingerprint:hash(nativeHeadCellMaterials),codeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-cell-art.ts'))),landmarkCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-cell-landmarks.ts'))),workbenchCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/head-cell-workbench.ts'))),workbench:'/api/topics/prehistoric-life/head-cells',inventory:'library/topics/prehistoric-life/head-cells/inventory-v1.json'},
  nativeActorGaze:{...nativeActorGazeDescription,handoff:'docs/topics/NATIVE-ACTOR-GAZE-HANDOFF.md',targetSourceCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-gaze-target.ts'))),physicalLungeCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/lunge.ts'))),publicationGuardCodeHash:hash(await fs.readFile(path.join(repo,'packages/scenes/source-publication.ts'))),scenePipelineCodeHash:hash(await fs.readFile(path.join(repo,'packages/scenes/index.ts'))),artworkTransactionCodeHash:hash(await fs.readFile(path.join(repo,'packages/director/artwork-repair.ts')))},
  nativeTracer:{version:'native-seat-tracer-2',scope:'unapproved-native-seat-motion-tracer',command:'npm run tracer:native-seat',runtimeVerified:false,productionAcceptance:false,finalExportAllowed:false,
    builder:'benchmarks/native-seat-tracer.ts',builderHash:hash(await fs.readFile(path.join(repo,'benchmarks/native-seat-tracer.ts'))),exporter:'scripts/native-seat-tracer.ts',exporterHash:hash(await fs.readFile(path.join(repo,'scripts/native-seat-tracer.ts'))),handoff:'docs/topics/NATIVE-SEAT-TRACER.md',
    opposingHeads:{...nativeDialogueDescription,command:'npm run tracer:native-seat -- --native-heads',builderFunction:'createNativeHeadSeatTracer',catalogCodeHash:hash(await fs.readFile(path.join(repo,'packages/topics/native-dialogue-candidates.ts'))),
      gestureProjection:{version:VIEW_SOURCE_GESTURE_PROJECTION_VERSION,file:'packages/animation/view-source-gesture.ts',codeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-source-gesture.ts')))},handoff:'docs/topics/NATIVE-DIALOGUE-ACTING.md'}},
  references,candidates:[...candidates,...headCandidates,...garmentCandidates],rejectedArtifacts:rejected,productionRig:null,
  headPack:{...headPack,prompts:['library/topics/prehistoric-life/rig-v1/head-prompts.json','library/topics/prehistoric-life/rig-v1/front-prompts.json'],codeHash:hash(await fs.readFile(path.join(repo,'packages/animation/forest-head-art.ts'))),cutoutCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/forest-cutout-head.ts'))),projectionCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/forest-head-projection.ts')))},
  bodyPack:{...bodyPack,codeHash:hash(await fs.readFile(path.join(repo,'packages/animation/forest-body-art.ts'))),walkCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/source-walk.ts'))),
    runCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/running.ts'))),spearCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/spear.ts'))),armShapeCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/source-arm.ts'))),compilerCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/compiler.ts'))),rigCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/rig.ts'))),cameraCodeHash:hash(await fs.readFile(path.join(repo,'packages/director/camera.ts'))),
    sourceBodyCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-source-body.ts'))),actingClockCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-acting-clock.ts'))),actingBindingCodeHash:hash(await fs.readFile(path.join(repo,'packages/actors/view-acting-clock.ts'))),
    secondaryCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/body-view-secondary.ts'))),secondaryMotionCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-secondary-motion.ts'))),
    viewCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/body-view-art.ts'))),viewContourCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/body-view-contours.ts'))),viewClothCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/body-view-cloth.ts'))),viewClothGeometryCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/view-cloth-geometry.ts'))),
    viewSeatCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/body-view-seat.ts'))),viewSeatRegistrationCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/native-seat-registration.ts'))),viewSeatCorrespondenceHash:hash(await fs.readFile(path.join(repo,'library/topics/prehistoric-life/native-seat-v1/correspondence-v1.json'))),lungeCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/lunge.ts'))),handCodeHash:hash(await fs.readFile(path.join(repo,'packages/animation/forest-hand.ts')))},
  poseArtwork:{scope:'static-artwork-only',inventory:'library/topics/prehistoric-life/pose-studies/inspection-v1.json',generatedImageCalls:14,staticVisionAdviceCalls:2,
    evidence:poseEvidence,approved:false,productionReady:false,generatedPosesIntegratedAsProductionRig:false,
    reviews:['docs/topics/reviews/gemini-pose-advice-v1.json','docs/topics/reviews/gemini-pose-advice-v3.json'],workflow:'docs/topics/AI-POSE-WORKFLOW.md'},
  nativeFrontManipulation:{...nativeManipulationDescription.ownFront,fingerprint:nativeManipulationDescription.fingerprint,handoffDocument:'docs/topics/FRONT-MANIPULATION-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-front-manipulation-binding.ts","packages/animation/native-contact-arm.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/body-view-front-registration.ts","packages/animation/compiler.ts","packages/animation/forest-body-art.ts","packages/animation/body-geometry.ts","packages/animation/rig.ts","packages/animation/body-view-cloth.ts","packages/animation/body-view-front-motion-binding.ts","packages/animation/source-arm.ts","packages/animation/arm-trajectory.ts","packages/animation/forest-hand.ts","packages/animation/view-source-body.ts","packages/animation/view-source-manipulation.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/director/acting-brief.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeProfileManipulation:{...nativeManipulationDescription.ownProfile,fingerprint:nativeManipulationDescription.fingerprint,handoffDocument:'docs/topics/PROFILE-MANIPULATION-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/native-contact-arm.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/body-view-oblique-registration.ts","packages/animation/compiler.ts","packages/animation/forest-body-art.ts","packages/animation/body-view-cloth.ts","packages/animation/body-view-profile-cloth-binding.ts","packages/animation/source-arm.ts","packages/animation/arm-trajectory.ts","packages/animation/forest-hand.ts","packages/animation/view-source-body.ts","packages/animation/view-source-manipulation.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/director/acting-brief.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeFrontSecondary:{...bodyViewDescription.secondaryCandidate.ownFront,fingerprint:bodyViewDescription.secondaryCandidate.fingerprint,handoff:'docs/topics/FRONT-SECONDARY-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-profile-secondary-binding.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/compiler.ts","packages/animation/view-secondary-motion.ts","packages/animation/view-cloth-geometry.ts","packages/animation/view-acting-clock.ts","packages/animation/view-expression-track.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/director/acting-brief.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeFrontMotion:{...bodyViewDescription.locomotionCandidate.ownFront,fingerprint:bodyViewDescription.locomotionCandidate.fingerprint,handoffDocument:'docs/topics/FRONT-MOTION-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-front-motion-binding.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-front-registration.ts","packages/animation/body-view-art.ts","packages/animation/body-view-cloth.ts","packages/animation/body-view-cloth-binding.ts","packages/animation/body-view-profile-cloth-binding.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-front-secondary-binding.ts","packages/animation/compiler.ts","packages/animation/rig.ts","packages/animation/source-walk.ts","packages/animation/view-cloth-geometry.ts","packages/animation/view-source-body.ts","packages/animation/view-source-gesture.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/director/acting-brief.ts","packages/host/schemas.ts","packages/animation/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeRearLocomotion:{...bodyViewDescription.locomotionCandidate.ownRear,fingerprint:bodyViewDescription.locomotionCandidate.fingerprint,handoff:'docs/topics/REAR-LOCOMOTION-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-front-secondary-binding.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/animation/body-view-cloth.ts","packages/animation/body-view-cloth-binding.ts","packages/animation/body-view-profile-cloth-binding.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/compiler.ts","packages/animation/view-cloth-geometry.ts","packages/animation/view-source-body.ts","packages/animation/view-source-gesture.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/director/acting-brief.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeProfileSecondary:{...bodyViewDescription.secondaryCandidate.ownProfile,fingerprint:bodyViewDescription.secondaryCandidate.fingerprint,handoff:'docs/topics/PROFILE-SECONDARY-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/animation/body-view-profile-secondary-binding.ts","packages/animation/body-view-secondary.ts","packages/animation/view-secondary-motion.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/compiler.ts","packages/animation/view-cloth-geometry.ts","packages/animation/view-source-body.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/director/camera.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeProfileLocomotion:{...bodyViewDescription.locomotionCandidate.ownProfile,fingerprint:bodyViewDescription.locomotionCandidate.fingerprint,handoff:'docs/topics/PROFILE-LOCOMOTION-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/director/camera.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-profile-secondary-binding.ts","packages/animation/body-view-profile-cloth-binding.ts","packages/animation/body-view-cloth.ts","packages/animation/body-view-cloth-binding.ts","packages/animation/body-view-basic-capabilities.ts","packages/animation/body-view-art.ts","packages/animation/compiler.ts","packages/animation/view-cloth-geometry.ts","packages/animation/view-source-body.ts","packages/animation/view-source-gesture.ts","packages/animation/view-acting-clock.ts","packages/actors/view-acting-clock.ts","packages/actors/model.ts","packages/actors/speech-clock.ts","packages/host/schemas.ts","packages/topics/body-workbench.ts"].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeBasicExpressions:{...bodyViewExpressionsDescription.ownBasicExpressions,fingerprint:bodyViewExpressionsDescription.fingerprint,handoff:'docs/topics/OWN-VIEW-EXPRESSIONS-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/director/camera.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-profile-secondary-binding.ts",'packages/animation/body-view-cloth.ts','packages/animation/body-view-profile-cloth-binding.ts','packages/animation/body-view-basic-expression-registration.ts','packages/animation/body-view-basic-eyes-registration.ts','packages/animation/body-view-basic-mouth-registration.ts','packages/animation/body-view-basic-capabilities.ts','packages/animation/body-view-expressions.ts','packages/animation/body-view-mouth.ts','packages/animation/body-view-eyes.ts','packages/animation/body-view-art.ts','packages/animation/compiler.ts','packages/animation/expression-pose.ts','packages/animation/view-expression-track.ts','packages/animation/view-acting-clock.ts','packages/actors/view-acting-clock.ts','packages/actors/speech-clock.ts','packages/host/schemas.ts','packages/topics/body-workbench.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeBasicSpeech:{...bodyViewMouthDescription.ownBasicMouth,handoff:'docs/topics/OWN-VIEW-SPEECH-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/director/camera.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-profile-secondary-binding.ts",'packages/animation/body-view-cloth.ts','packages/animation/body-view-profile-cloth-binding.ts','packages/animation/body-view-basic-mouth-registration.ts','packages/animation/body-view-basic-expression-registration.ts','packages/animation/body-view-expressions.ts','packages/animation/body-view-basic-capabilities.ts','packages/animation/body-view-mouth.ts','packages/animation/body-view-art.ts','packages/animation/compiler.ts','packages/animation/speech-clock.ts','packages/animation/view-acting-clock.ts','packages/actors/view-acting-clock.ts','packages/actors/speech-clock.ts','packages/host/schemas.ts','packages/topics/body-workbench.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeBasicEyes:{...bodyViewEyesDescription.ownBasicEyes,handoff:'docs/topics/OWN-VIEW-EYES-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/native-contact-arm.ts","packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/director/camera.ts","packages/animation/body-view-secondary.ts","packages/animation/body-view-profile-secondary-binding.ts",'packages/animation/body-view-cloth.ts','packages/animation/body-view-profile-cloth-binding.ts','packages/animation/body-view-expressions.ts','packages/animation/body-view-basic-expression-registration.ts','packages/animation/body-view-basic-mouth-registration.ts','packages/animation/body-view-basic-eyes-registration.ts','packages/animation/body-view-basic-capabilities.ts','packages/animation/body-view-eyes.ts','packages/animation/body-view-art.ts','packages/animation/compiler.ts','packages/animation/view-gaze-target.ts','packages/animation/view-acting-clock.ts','packages/actors/view-acting-clock.ts','packages/host/schemas.ts','packages/topics/body-workbench.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeObliqueRig:{...obliqueBodyRegistrationDescription,handoff:'docs/topics/PROFILE-REAR-RIG-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/director/camera.ts","packages/animation/body-view-profile-secondary-binding.ts",'packages/animation/body-view-profile-cloth-binding.ts','packages/animation/body-view-basic-expression-registration.ts','packages/animation/body-view-basic-mouth-registration.ts','packages/animation/view-gaze-target.ts','packages/animation/view-acting-clock.ts','packages/actors/view-acting-clock.ts','packages/animation/body-view-basic-eyes-registration.ts','packages/animation/body-view-basic-capabilities.ts','packages/animation/body-view-oblique-registration.ts','packages/animation/body-view-rest-arm.ts','packages/animation/body-view-front-registration.ts','packages/animation/body-view-registration.ts','packages/animation/body-view-art.ts','packages/animation/body-view-mouth.ts','packages/animation/body-view-rest-mouth.ts','packages/animation/body-view-eyes.ts','packages/animation/body-view-expressions.ts','packages/animation/body-view-cloth.ts','packages/animation/body-view-seat.ts','packages/animation/body-view-secondary.ts','packages/animation/native-contact-arm.ts','packages/animation/compiler.ts','packages/animation/rig.ts','packages/animation/forest-body-art.ts','packages/animation/forest-cutout-head.ts','packages/host/schemas.ts','packages/topics/body-workbench.ts','packages/topics/view-registration-workbench.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeFrontRig:{...frontBodyRegistrationDescription,handoff:'docs/topics/FRONT-BODY-RIG-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(["packages/animation/body-view-profile-manipulation-binding.ts","packages/animation/body-view-front-manipulation-binding.ts","packages/animation/body-view-front-secondary-binding.ts","packages/director/acting-brief.ts","packages/animation/body-view-rear-cloth-binding.ts","packages/animation/body-view-front-motion-binding.ts","packages/animation/body-view-profile-secondary-binding.ts",'packages/animation/body-view-profile-cloth-binding.ts','packages/animation/body-view-basic-expression-registration.ts','packages/animation/body-view-basic-mouth-registration.ts','packages/animation/view-gaze-target.ts','packages/animation/view-acting-clock.ts','packages/actors/view-acting-clock.ts','packages/animation/body-view-basic-eyes-registration.ts','packages/animation/body-view-basic-capabilities.ts','packages/animation/body-view-rest-arm.ts','packages/animation/body-view-oblique-registration.ts','packages/animation/forest-body-art.ts','packages/animation/forest-cutout-head.ts','packages/animation/body-view-front-registration.ts','packages/animation/body-view-registration.ts','packages/animation/body-view-art.ts','packages/animation/body-view-mouth.ts','packages/animation/body-view-rest-mouth.ts','packages/animation/body-view-eyes.ts','packages/animation/body-view-expressions.ts','packages/animation/body-view-cloth.ts','packages/animation/body-view-seat.ts','packages/animation/body-view-secondary.ts','packages/animation/native-contact-arm.ts','packages/animation/compiler.ts','packages/animation/rig.ts','packages/director/camera.ts','packages/host/schemas.ts','packages/topics/body-workbench.ts','packages/topics/view-registration-workbench.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  nativeViewCatalog:{...viewArtDescription,handoff:'docs/topics/PROFILE-REAR-RIG-HANDOFF.md',codeHashes:Object.fromEntries(await Promise.all(['packages/topics/view-art-workbench.ts','apps/server/index.ts','library/schemas/index.ts'].map(async file=>[file,hash(await fs.readFile(path.join(repo,file)))])))},
  authoredViewArtwork:{scope:'static-artwork-only',sourceRecords:viewEvidence.length,legacyStaticVisionAdviceCalls:2,builtInImageCallsThisSource:0,staticVisionAdviceAttemptsThisSource:0,previousFrontRearSource:{sourceVersion:'forest-tribe-0.91-front-rear-art',builtInImageCalls:8,staticVisionAdviceAttempts:1},previousRightProfileSource:{sourceVersion:'forest-tribe-0.90-right-profile-art',builtInImageCalls:5,staticVisionAdviceAttempts:2},evidence:viewEvidence,
    registered:false,registrationFlagScope:'all artwork approved/registered for production: false; raw generation metadata remains immutable',engineeringRegistrations:bodyViewDescription,approved:false,productionReady:false,integratedAsProductionRig:false,
    inventory:'library/topics/prehistoric-life/body-views/inspection-v1.json',workflow:'docs/topics/AUTHORED-VIEWS.md',
    reviews:['docs/topics/reviews/gemini-authored-views-advice-v1.json','docs/topics/reviews/gemini-authored-views-advice-v2.json']},
  actionPoseInspection:{file:'docs/topics/reviews/source-wrist-self-inspection-v1.json',scope:'developer-static-pose-inspection-only',pass:null,productionAcceptance:false,
    supersedes:{file:'docs/topics/reviews/source-spear-pose-self-inspection-v2.json',reason:'User rejected other arms and face distortion after 0.15. Earlier snapshots and AI artwork remain studies, not acceptance.'},
    currentRepair:'0.20 registers separate source cuff/palm candidates, migrates fixed arm endpoints independently of targets, keeps palm contact semantics and rotates immutable mittens by the forearm tangent. Developer frontal presets have reach reserve after migration; source poles/shaft offsets are explicit, think painter slots are discrete, interpolation checks cuffs and spear contacts. Static DOM inspection covers 144 actor-clock cards: 138 SVG, six unsupported head-turns. Real grasp, readable joint silhouettes, cloth/hair motion, other views, stance preparation and story integration remain pending; no motion/video acceptance.',
    sourceAdvice:{completedCalls:9,scope:'static-source-and-art-advice-only',reports:['docs/topics/reviews/gemini-arm-source-advice-v1.json','docs/topics/reviews/coder-arm-source-advice-v1.json','docs/topics/reviews/gemini-arm-source-advice-v2.json','docs/topics/reviews/gemini-arm-source-advice-v3.json','docs/topics/reviews/gemini-spear-pair-advice-v1.json','docs/topics/reviews/coder-spear-pair-advice-v1.json','docs/topics/reviews/gemini-view-lunge-advice-v1.json','docs/topics/reviews/coder-view-lunge-advice-v1.json','docs/topics/reviews/coder-wrist-palm-advice-v1.json'],assessment:'docs/topics/WRIST-PALM-IMPLEMENTATION.md',pass:null,productionAcceptance:false},workflow:'docs/topics/ARM-POSE-REPAIR.md'},
  walkPoseInspection:{file:'docs/topics/reviews/source-walk-pose-self-inspection-v1.json',scope:'developer-static-inspection-only',pass:null,productionAcceptance:false,
    currentRepair:'Distance-dependent C2 foot lift, bounded support transfer, speed-dependent arms and inferred XYZ knee projection. Isolated front-body poses only; full gait, seated transitions, authored side/rear body views and production acceptance remain pending.'},
  restCalibration:{status:'candidate',method:'SVG masks on full cutouts',reconstructedOccludedParts:false,naturalMotion:false,codeHash:hash(await fs.readFile(path.join(repo,'packages/topics/reference-puppet.ts')))},
  staticReview:{file:'docs/topics/reviews/karo-atlas-static-review-v1.json',pass:false,scope:'static-artwork-only',appliesTo:'atlas assembly v1, not revised cutout-mask assembly'},
  headStaticReview:{file:headReviewFile,pass:headReviewCurrent&&headReview?.result.pass===true,scope:'static-three-view-head-layer-only',appliesTo:headReview?.appliesTo,
    fingerprintMatches:headReviewCurrent,productionAcceptance:false,history:['docs/topics/reviews/head-layer-static-review-v2.json','docs/topics/reviews/head-layer-static-review-v3.json','docs/topics/reviews/head-layer-static-review-v4.json','docs/topics/reviews/front-head-static-review-v1.json']},
  headProjectionStaticReview:{file:projectionReviewFile,activeForBody:false,pass:false,historicalReviewPass:projectionReview?.result.pass===true,scope:projectionReview?.scope,appliesTo:projectionReview?.appliesTo,fingerprintMatches:projectionReviewCurrent,productionAcceptance:false,
    latestSelfInspection:'docs/topics/reviews/source-pose-art-self-inspection-v1.json',currentRepair:'The inferred yaw mesh and independently generated enlarged face glyphs were rejected by the user and removed from the body. Source cutout face now follows the registered neck/torso as one image. Provisional overlays, independent hair and authored partner-facing/profile/rear views remain pending.'},
  bodyStaticReview:{file:bodyReviewFile,pass:bodyReviewCurrent&&bodyReview?.result.pass===true,scope:bodyReview?.scope??'static-cuffs-and-seat-to-walk-poses-only',appliesTo:bodyReview?.appliesTo,
    fingerprintMatches:bodyReviewCurrent,productionAcceptance:false,history:['docs/topics/reviews/source-seat-static-review-v1.json','docs/topics/reviews/source-seat-static-review-v2.json','docs/topics/reviews/source-fold-static-review-v1.json','docs/topics/reviews/source-fold-static-review-v2.json','docs/topics/reviews/source-cuffs-static-review-v1.json','docs/topics/reviews/source-cuffs-static-review-v2.json'],
    latestSelfInspection:'docs/topics/reviews/source-waist-self-inspection-v2.json',
    currentRepair:'Karo two-cuff artwork v2 and common opaque UV surface now cover ordinary walking as well as seated plans. Pinned waist and a quadratic 25% area governor prevent detachment/inversion. Cuffs review v2 passed six poses on version 5. Waist review v1 on version 6 failed duplicate perimeter ink at 800ms; texture exclusion widened from 1.5 to 3.5 units afterward, with developer static inspection only. No current static or continuous-video acceptance.'},
  limitations:['AI cutouts and part atlases can redraw source details; none is a pixel-exact extraction guarantee.',
    'The atlas generator did not establish exact cell geometry. Define measured crops and pivots before use.',
    'Head-only inspection retains three historical authored drawings. Body uses one registered cutout source orientation without inferred yaw. Happy retains that cutout face, but the AI extraction is not guaranteed pixel identity. Partner-facing/profile/rear body/head views, accepted expressions, secondary layers and continuous motion remain pending.',
    'All 14 AI pose artifacts are unapproved. V1 changes limb style; V2 changes identity; ten V3 poses still require hand/silhouette/anatomy corrections and joint registration. Static model advice is not animation or production acceptance.',
    'Source clothing remains a candidate. Six-pose cuffs PASS applies to version 5 only. Version 6 waist review failed duplicate Karo ink; the subsequent wider texture exclusion has developer static inspection only. Area governor is not physical cloth or anatomy validation. Full clock, body views and final video remain unaccepted.',
    'Full-body color frames, layered rig, natural motion and the three complete video flows remain unaccepted.']});
console.log(JSON.stringify({references:references.length,candidates:candidates.length+headCandidates.length+garmentCandidates.length,headCandidates:headCandidates.length,garmentCandidates:garmentCandidates.length,rejected:rejected.length,productionReady:false}));
