export type Locale = 'vi' | 'en';
const en = {
  intentionalStatic: 'Intentional static shot', invalidTiming: 'The out point must follow the in point, and both must be valid times.',
  studio: 'Production studio', projects: 'Projects', newProject: 'New project', findProject: 'Find a project', local: 'Local production workspace',
  emptyProjects: 'Your stories start here.', emptyProjectsHelp: 'Create a project, add your narration, and shape every shot.', create: 'Create project', name: 'Project name', nameHint: '1–64 letters, digits, hyphens or underscores.', example: 'Start with the included example', cancel: 'Cancel', close: 'Close',
  welcome: 'Bring the story to life with animated actors.', welcomeHelp: 'Enter a complete narration or upload WAV/SRT, choose stick figures or mini robots, and let the characters act within the story.', inputStep: 'Add narration', inputHelp: 'Script, WAV or SRT; choose the character style and a narration voice.', boardStep: 'Direct the story', boardHelp: 'Review story roles, situations and performances; lock details that matter.', deliverStep: 'Make the final cut', deliverHelp: 'Preview, refine, review quality and download the film.',
  language: 'Interface language', inputs: 'Source & assets', refresh: 'Refresh', resume: 'Resume production', stopAfter: 'Stop after', running: 'Production in progress', stopHint: 'The job finishes after the selected stage. Choose the next stage before starting another run.', runHint: 'Resume from the last completed stage.', waiting: 'Ready to continue', completed: 'Job completed', failed: 'Job failed', loading: 'Loading…', saved: 'Changes saved', created: 'Project created', uploaded: 'Files uploaded', approved: 'Approved', locked: 'Locked', unlocked: 'Unlocked',
  shots: 'Shots', chapters: 'Chapters', allChapters: 'All chapters', findShot: 'Find a shot', noShots: 'The storyboard is waiting.', noShotsHelp: 'Add narration and run production through Storyboard to begin directing.', noMatches: 'No matching items.', preview: 'Preview', composition: 'Live scenes', draft: 'Draft film', final: 'Final film', noPreview: 'Your film will appear here.', noPreviewHelp: 'Build scenes for an interactive preview, or render a draft to watch the film.', play: 'Play', pause: 'Pause', previous: 'Previous shot', next: 'Next shot', start: 'Go to start', previewMode: 'Preview source', time: 'Playhead time', mute: 'Mute narration', unmute: 'Unmute narration', unavailablePreview: 'This preview is not available yet.', stalePreview: 'Preview belongs to an earlier build. Resume production to update it.',
  timeline: 'Timeline', scrub: 'Scrub timeline', zoom: 'Timeline zoom', narration: 'Narration', storyboard: 'Storyboard', scene: 'Scene', characters: 'Characters', reports: 'Delivery & QC', logs: 'Production log', inspector: 'Shot details', selectShot: 'Select a shot to direct it.', subject: 'Subject', visual: 'Visual direction', type: 'Scene type', camera: 'Camera', shotSize: 'Shot size', movement: 'Movement', angle: 'Angle', caption: 'On-screen caption', captionHint: 'Leave empty for no on-screen caption.', duration: 'Timing', inPoint: 'In point', outPoint: 'Out point', timingHint: 'Cuts use existing narration, word or beat boundaries. Neighboring shots adjust to keep complete coverage.', recipe: 'Shot recipe', automatic: 'Automatic', motion: 'Motion notes', transitions: 'Transitions', transitionIn: 'In', transitionOut: 'Out', assets: 'Assets & poses', asset: 'Asset', assetSource: 'Local asset', generatedAsset: 'Resolve automatically', pose: 'Character pose', version: 'Character version', saveShot: 'Save shot', rebuildShot: 'Rebuild this shot', rebuildHint: 'Build scenes first. Rebuild respects locked shots.', lockShot: 'Lock shot', unlockShot: 'Unlock shot', shotLocked: 'Unlock the shot or storyboard to edit.',
  approveBoard: 'Approve storyboard', lockBoard: 'Lock storyboard', unlockBoard: 'Unlock storyboard', boardHint: 'Edit the complete storyboard to adjust several shots together. Narration timing and coverage are validated on save.', saveBoard: 'Save storyboard', editJson: 'Structured editor', noArtifact: 'This document is not available yet.', saveNarration: 'Save narration', narrationHint: 'Edit the words. Original timestamps stay fixed.', source: 'Supplemental source', sourceHint: 'Optional supporting material. The selected narration controls spoken content.', saveSource: 'Save source', dirty: 'Unsaved changes', discard: 'Discard unsaved changes?', discardHelp: 'Your saved version is safe. Changes in this editor will be lost.', reload: 'Reload saved version',
  saveScene: 'Save scene', sceneHint: 'Edit this shot’s HTML, CSS and animation. Save validates the scene and updates the preview.', file: 'File', noScene: 'Build this shot’s scene to edit its implementation.', approveCharacters: 'Approve characters', lockCharacters: 'Lock character bible', unlockCharacters: 'Unlock character bible', saveCharacters: 'Save characters', characterHint: 'Keep identity consistent. Unlock a character explicitly to change its identity; poses can vary between shots.', noCharacters: 'No characters have been planned yet.', lockIdentity: 'Lock identity', unlockIdentity: 'Unlock identity', editCharacter: 'Edit characters', reference: 'Reference',
  delivery: 'Delivery', downloads: 'Production files', download: 'Download', noDownloads: 'Production files will appear as stages complete.', qc: 'Quality control', qcPending: 'Quality review has not run yet.', pass: 'Passed', fail: 'Needs attention', review: 'Visual review', costs: 'Production cost', costPending: 'Cost information will appear after production begins.', calls: 'Model calls', tokens: 'Tokens', total: 'Total', issues: 'Issues', noIssues: 'No reported issues.', contactSheet: 'Contact sheet', viewContact: 'View contact sheet',
  logSource: 'Log source', orchestrator: 'Production', models: 'Model calls', renderer: 'Rendering', ffmpeg: 'Audio & delivery', logEmpty: 'No log entries yet.', logTail: 'Showing the most recent log entries.',
  uploadTitle: 'Bring your story into the studio.', uploadHelp: 'Add a Markdown story, SRT subtitles, a WAV voice track and reference assets. All files belong to this project.', sourceFile: 'Source · .md', subtitleFile: 'Timed subtitles · .srt', audioFile: 'Narration audio · .wav', assetFiles: 'Reference assets', upload: 'Upload files', uploadLimits: 'Up to 12 files, 128 MB per file and 256 MB per batch. Reference images/documents: 16 MB; music: 32 MB; video: 128 MB.', fileList: 'Project assets', noAssets: 'No reference assets yet.', replaceHint: 'Source, subtitles and narration replace the current inputs. Production restarts from the source.', uploadProgress: 'Uploading files…', requestFailed: 'The operation failed. Try again.', connectionLost: 'Cannot reach the studio. Check that the local server is running, then refresh.', conflict: 'This file changed elsewhere. Reload the saved version before editing again.', lockedError: 'This item is locked. Unlock it before editing.', busyError: 'This project is busy. Wait for production to finish.', invalidJson: 'Invalid JSON. Check commas, quotes and brackets.', approvalNeeded: 'Approval is needed to continue.', stageNEW: 'Source', stageINGESTED: 'Ingest', stageTIMED: 'Timeline', stageANALYZED: 'Story analysis', stageSTORYBOARDED: 'Storyboard', stageASSETS_READY: 'Assets', stageSCENES_READY: 'Scenes', stageDRAFT_RENDERED: 'Draft', stageREVIEWED: 'Visual review', stageREPAIRED: 'Refinement', stageFINAL_RENDERED: 'Final render', stageQC_PASSED: 'Quality control', stageDONE: 'Delivery',
} as const;
const vi: Record<keyof typeof en, string> = {
  intentionalStatic: 'Cảnh tĩnh có chủ ý', invalidTiming: 'Điểm ra phải lớn hơn điểm vào và cả hai phải là thời gian hợp lệ.',
  studio: 'Xưởng sản xuất', projects: 'Dự án', newProject: 'Dự án mới', findProject: 'Tìm dự án', local: 'Không gian sản xuất cục bộ',
  emptyProjects: 'Mỗi câu chuyện bắt đầu từ đây.', emptyProjectsHelp: 'Tạo dự án, thêm lời kể và đạo diễn từng cảnh.', create: 'Tạo dự án', name: 'Tên dự án', nameHint: '1–64 chữ cái không dấu, số, dấu gạch ngang hoặc gạch dưới.', example: 'Bắt đầu từ ví dụ có sẵn', cancel: 'Hủy', close: 'Đóng',
  welcome: 'Kể câu chuyện bằng diễn viên hoạt hình.', welcomeHelp: 'Nhập lời kể hoặc tải WAV/SRT, chọn người que hoặc robot mini, để nhân vật đóng vai trong câu chuyện.', inputStep: 'Nhập lời kể', inputHelp: 'Kịch bản, WAV hoặc SRT; chọn kiểu tạo hình và giọng kể.', boardStep: 'Đạo diễn câu chuyện', boardHelp: 'Xem vai diễn, tình huống và diễn xuất; khóa những chi tiết cần giữ.', deliverStep: 'Hoàn thiện thước phim', deliverHelp: 'Xem trước, tinh chỉnh, kiểm tra chất lượng và tải phim.',
  language: 'Ngôn ngữ giao diện', inputs: 'Nguồn & tư liệu', refresh: 'Làm mới', resume: 'Tiếp tục sản xuất', stopAfter: 'Dừng sau', running: 'Đang sản xuất', stopHint: 'Tác vụ kết thúc sau giai đoạn đã chọn. Chọn mốc tiếp theo trước khi chạy lượt mới.', runHint: 'Tiếp tục từ giai đoạn hoàn thành gần nhất.', waiting: 'Sẵn sàng tiếp tục', completed: 'Tác vụ đã hoàn thành', failed: 'Tác vụ thất bại', loading: 'Đang tải…', saved: 'Đã lưu chỉnh sửa', created: 'Đã tạo dự án', uploaded: 'Đã tải tệp lên', approved: 'Đã duyệt', locked: 'Đã khóa', unlocked: 'Đã mở khóa',
  shots: 'Shot', chapters: 'Chương', allChapters: 'Tất cả chương', findShot: 'Tìm shot', noShots: 'Storyboard đang chờ câu chuyện.', noShotsHelp: 'Thêm lời kể và chạy đến giai đoạn Storyboard để bắt đầu đạo diễn.', noMatches: 'Không có kết quả phù hợp.', preview: 'Xem trước', composition: 'Cảnh tương tác', draft: 'Phim nháp', final: 'Phim hoàn chỉnh', noPreview: 'Thước phim sẽ xuất hiện tại đây.', noPreviewHelp: 'Dựng cảnh để xem tương tác, hoặc kết xuất phim nháp để xem toàn bộ.', play: 'Phát', pause: 'Tạm dừng', previous: 'Shot trước', next: 'Shot tiếp', start: 'Về đầu', previewMode: 'Nguồn xem trước', time: 'Thời gian đầu phát', mute: 'Tắt tiếng lời kể', unmute: 'Bật tiếng lời kể', unavailablePreview: 'Bản xem trước này chưa sẵn sàng.', stalePreview: 'Đây là bản dựng trước. Tiếp tục sản xuất để cập nhật.',
  timeline: 'Trục thời gian', scrub: 'Di chuyển đầu phát', zoom: 'Thu phóng timeline', narration: 'Lời kể', storyboard: 'Storyboard', scene: 'Cảnh', characters: 'Nhân vật', reports: 'Thành phẩm & QC', logs: 'Nhật ký sản xuất', inspector: 'Chi tiết shot', selectShot: 'Chọn một shot để đạo diễn.', subject: 'Chủ thể', visual: 'Chỉ dẫn hình ảnh', type: 'Loại cảnh', camera: 'Máy quay', shotSize: 'Cỡ cảnh', movement: 'Chuyển động', angle: 'Góc máy', caption: 'Chữ trên màn hình', captionHint: 'Để trống nếu không cần chữ trên màn hình.', duration: 'Thời gian', inPoint: 'Điểm vào', outPoint: 'Điểm ra', timingHint: 'Điểm cắt dùng mốc narration, từ hoặc beat có sẵn. Shot liền kề được điều chỉnh để giữ phủ đủ thời gian.', recipe: 'Công thức cảnh', automatic: 'Tự động', motion: 'Chỉ dẫn chuyển động', transitions: 'Chuyển cảnh', transitionIn: 'Vào', transitionOut: 'Ra', assets: 'Tư liệu & tư thế', asset: 'Tư liệu', assetSource: 'Tư liệu cục bộ', generatedAsset: 'Tự động tìm tư liệu', pose: 'Tư thế nhân vật', version: 'Phiên bản nhân vật', saveShot: 'Lưu shot', rebuildShot: 'Dựng lại shot này', rebuildHint: 'Dựng cảnh trước. Tác vụ dựng lại tôn trọng các shot đã khóa.', lockShot: 'Khóa shot', unlockShot: 'Mở khóa shot', shotLocked: 'Mở khóa shot hoặc storyboard để chỉnh sửa.',
  approveBoard: 'Duyệt storyboard', lockBoard: 'Khóa storyboard', unlockBoard: 'Mở khóa storyboard', boardHint: 'Chỉnh toàn bộ storyboard để thay đổi nhiều shot cùng lúc. Hệ thống kiểm tra thời gian và độ phủ khi lưu.', saveBoard: 'Lưu storyboard', editJson: 'Trình sửa cấu trúc', noArtifact: 'Tài liệu này chưa sẵn sàng.', saveNarration: 'Lưu lời kể', narrationHint: 'Chỉnh nội dung lời kể. Các mốc thời gian gốc được giữ cố định.', source: 'Tài liệu bổ trợ', sourceHint: 'Tài liệu bổ trợ tùy chọn; lời kể do luồng đầu vào được chọn quyết định.', saveSource: 'Lưu nguồn truyện', dirty: 'Có chỉnh sửa chưa lưu', discard: 'Bỏ chỉnh sửa chưa lưu?', discardHelp: 'Bản đã lưu vẫn an toàn. Các thay đổi trong trình sửa này sẽ bị mất.', reload: 'Tải lại bản đã lưu',
  saveScene: 'Lưu cảnh', sceneHint: 'Chỉnh HTML, CSS và chuyển động của shot. Khi lưu, cảnh được kiểm tra và bản xem trước được cập nhật.', file: 'Tệp', noScene: 'Dựng cảnh cho shot này để chỉnh cách thể hiện.', approveCharacters: 'Duyệt nhân vật', lockCharacters: 'Khóa hồ sơ nhân vật', unlockCharacters: 'Mở khóa hồ sơ nhân vật', saveCharacters: 'Lưu nhân vật', characterHint: 'Giữ ngoại hình nhất quán. Mở khóa từng nhân vật khi đổi nhận diện; tư thế có thể đổi giữa các shot.', noCharacters: 'Chưa có nhân vật được lên kế hoạch.', lockIdentity: 'Khóa nhận diện', unlockIdentity: 'Mở khóa nhận diện', editCharacter: 'Chỉnh nhân vật', reference: 'Tham chiếu',
  delivery: 'Thành phẩm', downloads: 'Tệp sản xuất', download: 'Tải xuống', noDownloads: 'Tệp sản xuất xuất hiện khi các giai đoạn hoàn thành.', qc: 'Kiểm tra chất lượng', qcPending: 'Chưa chạy kiểm tra chất lượng.', pass: 'Đạt', fail: 'Cần xử lý', review: 'Duyệt hình ảnh', costs: 'Chi phí sản xuất', costPending: 'Thông tin chi phí xuất hiện sau khi bắt đầu sản xuất.', calls: 'Lượt gọi model', tokens: 'Token', total: 'Tổng', issues: 'Vấn đề', noIssues: 'Không có vấn đề được báo cáo.', contactSheet: 'Bảng khung hình', viewContact: 'Xem bảng khung hình',
  logSource: 'Nguồn nhật ký', orchestrator: 'Sản xuất', models: 'Lượt gọi model', renderer: 'Kết xuất', ffmpeg: 'Âm thanh & thành phẩm', logEmpty: 'Chưa có nhật ký.', logTail: 'Đang hiển thị các mục nhật ký gần nhất.',
  uploadTitle: 'Đưa câu chuyện vào xưởng phim.', uploadHelp: 'Thêm nguồn Markdown, phụ đề SRT, giọng đọc WAV và tư liệu tham chiếu. Mọi tệp thuộc dự án này.', sourceFile: 'Nguồn truyện · .md', subtitleFile: 'Phụ đề có thời gian · .srt', audioFile: 'Giọng đọc · .wav', assetFiles: 'Tư liệu tham chiếu', upload: 'Tải tệp lên', uploadLimits: 'Tối đa 12 tệp, 128 MB mỗi tệp và 256 MB mỗi lượt. Ảnh/tài liệu: 16 MB; nhạc: 32 MB; video: 128 MB.', fileList: 'Tư liệu dự án', noAssets: 'Chưa có tư liệu tham chiếu.', replaceHint: 'Nguồn, phụ đề và giọng đọc thay thế đầu vào hiện tại. Quy trình bắt đầu lại từ nguồn.', uploadProgress: 'Đang tải tệp lên…', requestFailed: 'Thao tác thất bại. Vui lòng thử lại.', connectionLost: 'Không kết nối được với xưởng phim. Kiểm tra máy chủ cục bộ rồi làm mới.', conflict: 'Tệp đã thay đổi ở nơi khác. Tải lại bản đã lưu trước khi chỉnh tiếp.', lockedError: 'Mục này đang khóa. Mở khóa trước khi chỉnh sửa.', busyError: 'Dự án đang bận. Chờ sản xuất hoàn tất.', invalidJson: 'JSON không hợp lệ. Kiểm tra dấu phẩy, dấu nháy và ngoặc.', approvalNeeded: 'Cần phê duyệt để tiếp tục.', stageNEW: 'Nguồn', stageINGESTED: 'Nhập liệu', stageTIMED: 'Timeline', stageANALYZED: 'Phân tích truyện', stageSTORYBOARDED: 'Storyboard', stageASSETS_READY: 'Tư liệu', stageSCENES_READY: 'Dựng cảnh', stageDRAFT_RENDERED: 'Phim nháp', stageREVIEWED: 'Duyệt hình ảnh', stageREPAIRED: 'Tinh chỉnh', stageFINAL_RENDERED: 'Kết xuất cuối', stageQC_PASSED: 'Chất lượng', stageDONE: 'Thành phẩm',
};
export type TextKey = keyof typeof en;
export function translator(locale: Locale) { return (key: TextKey): string => locale === 'vi' ? vi[key] : en[key]; }
