import {escapeHtml,hash} from '../core/utils.js';
import {headTurnInventory,headTurnMaterial} from './head-turn-art.js';
import {headTurnDraft,headTurnSourceBinding} from './head-turn-landmarks.js';
import {HeadTurnFileSchema} from './head-turn-schemas.js';

export async function headTurnWorkbench(repo:string,selected?:string){
  const inventory=await headTurnInventory(repo);
  if(selected)HeadTurnFileSchema.parse(selected);
  const current=selected?inventory.find(m=>m.file===selected):inventory.find(m=>m.file==='lila-head-turn-v2.png')??inventory[0];
  if(!current)throw new Error('Unknown head turn material');
  const cards=inventory.map(m=>`<section><h2>${escapeHtml(m.file)}</h2><p>${m.width}×${m.height} ·4×4 ô đo thật ·${m.transparentPixels} pixel alpha0. Góc trong prompt chưa được đo. SHA256: <code>${m.sha256}</code></p><img class="atlas" src="/api/topics/prehistoric-life/head-turn-art/${m.file}" alt="${m.actor}16 hình đầu ứng viên"><ul>${m.findings.map(f=>`<li>Ô ${f.cells.join(', ')}: ${escapeHtml(f.note)}</li>`).join('')}</ul><a href="?file=${m.file}#editor">Đo landmark bộ này</a></section>`).join('');
  const data=escapeHtml(JSON.stringify({material:current,draft:headTurnDraft(current),source:headTurnSourceBinding(current),fingerprint:hash(current)}));
  return `<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quay đầu Lila/Karo — artwork và landmark</title><style>
body{font:16px system-ui;color:#362215;background:#ece5d6;margin:24px}main{max-width:1200px;margin:auto}section{padding:24px;background:#fff7e5;border-radius:16px;margin:24px 0}h1{font-size:28px}p,li{line-height:1.5}a{color:#684516}code{overflow-wrap:anywhere}.atlas{width:100%;max-width:950px;background:#fff7e5}.pair{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.reference{max-height:360px;max-width:100%}#cell-view{overflow:hidden;background:#fff7e5;width:100%;height:640px;touch-action:manipulation;border:1px solid #b88753}.controls{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}button,select,input{font:inherit;padding:8px}label{display:block;margin:12px 0}textarea{font:14px monospace;width:100%;min-height:80px;box-sizing:border-box}#result{white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto}#markers text{font:8px sans-serif;fill:#092f63;paint-order:stroke;stroke:#fff;stroke-width:1px}#markers circle{fill:#21a8ff;stroke:#fff;stroke-width:1px}@media(max-width:780px){.pair{grid-template-columns:1fr}body{margin:12px}#cell-view{height:480px}}
</style><main><h1>Quay đầu — artwork còn cần sửa</h1><p>Đây là bàn đo ảnh tĩnh. Cả hai bộ vẫn trôi tóc/râu và góc mặt ở một số ô, chưa đăng ký vào rig. V2 là lần sửa thử, không tự thay V1 trong scene. Không có preview chuyển động, không xuất video, không duyệt production tại đây.</p><p><a href="/api/topics/prehistoric-life/view-registration">Rig góc thân hiện có</a> · <a href="/api/topics/prehistoric-life/view-art">Artwork góc thân</a></p>
<section id="editor" data-head-turn="${data}"><h2>Đo ${escapeHtml(current.file)}</h2><div class="pair"><div><svg id="cell-view" xmlns="http://www.w3.org/2000/svg"><image id="source-image" width="${current.width}" height="${current.height}" href="/api/topics/prehistoric-life/head-turn-art/${current.file}"/><g id="markers"></g></svg><div class="controls"><button id="previous" type="button">Ô trước</button><strong id="cell-label"></strong><button id="next" type="button">Ô sau</button></div></div><div><img class="reference" src="/api/topics/prehistoric-life/references/reference-${current.actor}-full.png" alt="Chuẩn gốc ${current.actor}"><p>Chọn điểm rồi bấm trên ảnh. Tọa độ ghi theo pixel nguồn, không theo kích thước màn hình. Mắt trái/phải là vị trí trên ảnh, không phải tay trái/phải nhân vật.</p><label>Điểm đo<select id="landmark"><option value="neck">Điểm gắn cổ</option><option value="neckTop">Trục cổ phía trên</option><option value="chin">Cằm</option><option value="nose">Mũi</option><option value="mouth">Tâm miệng</option><option value="screen-left">Mắt phía trái ảnh</option><option value="screen-right">Mắt phía phải ảnh</option><option value="faceContour">Thêm điểm viền mặt</option></select></label><button id="clear-point" type="button">Xóa điểm đã chọn</button><label>Góc thực do người đo ghi (độ)<input id="yaw" type="number" min="-90" max="90" step="0.1"></label><label>Đối chiếu tạo hình<select id="review"><option value="unreviewed">Chưa kiểm</option><option value="needs-redraw">Cần vẽ lại</option><option value="candidate">Ứng viên sau đối chiếu</option></select></label><label>Phía tóc buộc theo cơ thể<select id="ponytail"><option value="">Chưa xác định</option><option value="anatomical-left">Trái cơ thể</option><option value="anatomical-right">Phải cơ thể</option><option value="behind">Bị che phía sau</option><option value="not-applicable">Không có (Karo)</option></select></label><label>Mắt bị che<select id="occlusion"><option value="">Không ghi che khuất</option><option value="nose">Mũi che</option><option value="face-contour">Viền mặt che</option><option value="hair">Tóc che</option></select></label><button id="set-occlusion" type="button">Ghi che khuất cho mắt đang chọn</button><label>Ghi chú<textarea id="notes"></textarea></label></div></div><label>Landmark ô hiện tại (JSON, chỉ đọc)<textarea id="cell-json" readonly></textarea></label><div class="controls"><button id="check" type="button">Kiểm tra bản đo</button><button id="download" type="button">Tải JSON bản đo</button><label>Nạp lại JSON bản đo<input id="import" type="file" accept=".json,application/json"></label></div><p>Kiểm tra chỉ báo điểm còn thiếu/sai. Bản đo không ghi vào rig hoặc thư viện và không duyệt ảnh. Chưa gán tọa độ mắt/miệng từ một góc sang góc khác.</p><pre id="result" role="status">Chưa kiểm tra bản đo.</pre></section>${cards}</main><script src="/api/topics/prehistoric-life/head-turn-editor.js" defer></script></html>`;
}
export async function headTurnImage(repo:string,file:string){return (await headTurnMaterial(repo,file)).bytes;}

/** Self-hosted source for the landmark editor. It is not a scene/animation
 * renderer: no GSAP, RAF, audio, video, body sampling or model calls. */
export const headTurnEditorScript=String.raw`(()=>{
'use strict';
const $=id=>document.getElementById(id),editor=$('editor'),initial=JSON.parse(editor.dataset.headTurn);
const material=initial.material;let draft=initial.draft,index=0,editRevision=0,importRevision=0;
const svg=$('cell-view'),ns='http://www.w3.org/2000/svg';
const cell=()=>draft.cells[index];
const showError=error=>{$('result').textContent=String(error instanceof Error?error.message:error);};
function saveFields(){const c=cell(),before=JSON.stringify(c),yaw=$('yaw').value; if(yaw==='')delete c.yawDeg;else c.yawDeg=Number(yaw);c.review=$('review').value;c.notes=$('notes').value;const side=$('ponytail').value;if(side)c.ponytailSide=side;else delete c.ponytailSide;if(before!==JSON.stringify(c))editRevision++;}
function draw(){const c=cell(),r=material.cells[index].region;svg.setAttribute('viewBox',[r.x,r.y,r.width,r.height].join(' '));$('cell-label').textContent='Ô '+c.index+' /16';$('previous').disabled=index===0;$('next').disabled=index===15;
 $('yaw').value=c.yawDeg??'';$('review').value=c.review;$('notes').value=c.notes;$('ponytail').value=c.ponytailSide??'';$('cell-json').value=JSON.stringify(c,null,2);$('markers').replaceChildren();
 const points=Object.entries(c).filter(([k])=>['neck','neckTop','chin','nose','mouth'].includes(k));for(const [slot,e] of Object.entries(c.eyes??{}))if(e.visible)points.push([slot,e.center]);(c.faceContour??[]).forEach((p,i)=>points.push(['contour'+(i+1),p]));
 for(const [label,p] of points){const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.setAttribute('r',2.5);const text=document.createElementNS(ns,'text');text.setAttribute('x',p.x+4);text.setAttribute('y',p.y-4);text.textContent=label;$('markers').append(dot,text);}
 if(c.faceContour?.length>1){const line=document.createElementNS(ns,'polyline');line.setAttribute('points',c.faceContour.map(p=>p.x+','+p.y).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#0080ba');line.setAttribute('stroke-width','1');$('markers').prepend(line);}
}
svg.addEventListener('pointerdown',event=>{try{saveFields();const matrix=svg.getScreenCTM();if(!matrix)throw new Error('Không đọc được tọa độ ảnh');const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse()),r=material.cells[index].region;
 if(point.x<r.x||point.x>=r.x+r.width||point.y<r.y||point.y>=r.y+r.height)return;const p={x:Math.max(r.x,Math.min(r.x+r.width-.01,Math.round(point.x*100)/100)),y:Math.max(r.y,Math.min(r.y+r.height-.01,Math.round(point.y*100)/100))},key=$('landmark').value,c=cell();
 if(key==='faceContour'){c.faceContour??=[];if(c.faceContour.length>=32)throw new Error('Tối đa32 điểm viền');c.faceContour.push(p);}else if(key==='screen-left'||key==='screen-right'){c.eyes??={};c.eyes[key]={visible:true,center:p};}else c[key]=p;editRevision++;draw();}catch(error){showError(error);}});
$('previous').addEventListener('click',()=>{saveFields();if(index>0)index--;draw();});$('next').addEventListener('click',()=>{saveFields();if(index<15)index++;draw();});
$('clear-point').addEventListener('click',()=>{saveFields();const key=$('landmark').value;if(key==='screen-left'||key==='screen-right'){if(cell().eyes)delete cell().eyes[key];}else delete cell()[key];editRevision++;draw();});
$('set-occlusion').addEventListener('click',()=>{saveFields();const key=$('landmark').value,occludedBy=$('occlusion').value;if(!['screen-left','screen-right'].includes(key)||!occludedBy){showError('Chọn một mắt và phần che mắt trước.');return;}cell().eyes??={};cell().eyes[key]={visible:false,occludedBy};editRevision++;draw();});
const matchesDisplayed=candidate=>Object.entries(initial.source).every(([key,value])=>candidate?.[key]===value);
async function checked(candidate){if(!matchesDisplayed(candidate))throw new Error('Bản đo khác ảnh/nhân vật đang hiển thị; hãy mở đúng bộ ảnh trước.');const response=await fetch('/api/topics/prehistoric-life/head-turn-draft/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:initial.source,draft:candidate})});const result=await response.json();if(!response.ok)throw new Error(result.message??'Bản đo không hợp lệ');if(!matchesDisplayed(result.draft))throw new Error('Kết quả kiểm tra không khớp ảnh đang hiển thị.');return result;}
$('check').addEventListener('click',async()=>{try{saveFields();const result=await checked(draft);$('result').textContent=JSON.stringify(result,null,2);}catch(error){showError(error);}});
$('download').addEventListener('click',async()=>{try{saveFields();const result=await checked(draft);const url=URL.createObjectURL(new Blob([JSON.stringify(result.draft,null,2)+'\n'],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=material.file.replace('.png','-landmarks-draft.json');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('result').textContent='Đã tải snapshot được kiểm; còn '+result.pending.length+' điểm cần xử lý. Các chỉnh sửa mới trong browser được giữ. Chưa đăng ký hoặc duyệt rig.';}catch(error){showError(error);}});
$('import').addEventListener('change',async()=>{const ticket=++importRevision;try{saveFields();const revision=editRevision,file=$('import').files?.[0];if(!file)return;if(file.size>200*1024)throw new Error('Bản đo quá lớn');const result=await checked(JSON.parse(await file.text()));saveFields();if(ticket!==importRevision||revision!==editRevision)throw new Error('Bạn đã chỉnh bản đo khi đang nạp; giữ các chỉnh sửa, hãy nạp lại nếu cần.');draft=result.draft;editRevision++;draw();$('result').textContent=JSON.stringify(result,null,2);}catch(error){showError(error);}finally{if(ticket===importRevision)$('import').value='';}});
for(const id of ['yaw','review','notes','ponytail']){ $(id).addEventListener('input',saveFields); $(id).addEventListener('change',saveFields); }
draw();
})();`;
